(function (){ var e="",aa="\x00",h=" ",ba=" (",ca=" (Google)",da=" icon",ea=' name="',fa=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)',ha=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678) alpha(opacity=50)',ia=' type="',ja=" visibility",ka=" x ",la='"',ma='"trebuchet ms",verdana,arial,sans-serif',na="#",oa="#000",pa="#fff",qa="%",ra="%$1",
sa="%2525",ta="%s",l="&",va="&#0;",wa="&#39;",xa="&action=",ya="&amp;",za="&func=",Aa="&gt;",Ba="&lt;",Ca="&nbsp;",Da="&quot;",Ea="&sectionId=",Fa="&widgetId=",Ga="&widgetType=",Ha="'",Ia="' of type ",Ja="(",Ka="(\\d*)(\\D*)",La=")",Ma="*",Na=",",Oa="-140px",Pa="-225px",Qa=".",Ra=".01",Ta=".5",Ua=".js",Va=".previewMode .postCommentButtonHolder { padding-top: 22px; }\n",Wa=".x",Xa=".y",Ya="/",Za="//",$a="//img2.blogblog.com/img/icon_inprogress.gif",ab="/comment-iframe-bg.g",bb="/rearrange?blogID=",
cb="0",db="1",eb="100%",fb="1000",gb="10px",hb="1px solid #aaa",ib="1px solid transparent",jb="200px",kb="24px",lb="28px",mb="50% 0",nb="600px",ob="75px",pb=":",qb=": ",rb=";\nfont-family: ",sb=";}\n",tb="<",n="=",ub=">",vb="?",wb="?widgetId=",xb="@",yb="AIM",zb="AIM username:",Ab="ANON",Bb="ARIA attribute cannot be empty.",Cb="An error occurred while contacting the server.",Db="An object listener must have handleEvent method.",Eb="Anonymous",Fb="Assertion failed",Gb="BODY",Hb="CSS1Compat",Ib="CURRENT",
Jb="Comment should not be empty",Kb="Content length exceeds 1MB. Please abridge.",Lb="Content-Type",Mb="DIV",Nb="Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?",Ob="Expected number but got %s: %s.",Pb="Expected string but got %s: %s.",Qb="FIELDSET",Rb="GET",Sb="GOOGLE",Tb="Google Account",Ub="HEAD",Vb="INPUT",Wb="LJ",Xb="Listener can not be null.",Yb="LiveJournal",Zb="LiveJournal username:",$b="MSXML2.XMLHTTP",ac="MSXML2.XMLHTTP.3.0",bc="MSXML2.XMLHTTP.6.0",
cc="Microsoft Internet Explorer",dc="Microsoft.XMLHTTP",ec="NAMEURL",fc="NONE",gc="Name should not be empty",hc="Name/URL",ic="No such ARIA attribute expanded",jc="No such ARIA role tab",kc="Node cannot be null or undefined.",lc="OPENID",mc="OpenID",nc="POST",oc="Please choose a profile",pc="Preview",qc="SCRIPT",rc="STYLE",sc="SafeStyleSheet{",tc="Select profile...",uc="SubscribeByEmail",vc="TP",wc="The URL should not be empty",xc="The username should not be empty",yc="TypePad",zc="TypePad username:",
Ac="UnsubscribeByEmail",Bc="WP",Cc="WordPress",Dc="WordPress username:",Ec="X",Fc="[object Array]",Gc="[object Function]",Hc="[object Window]",Ic="]",Jc="_",Kc="_OnWidgetDeleted",Lc="__gjsload__",Mc="_asynchronousFileUploadIframe",Nc="_changeImageLink",Oc="_imageChoiceTable",Pc="_imgFileNameError",Qc="_imgFileNameInput",Rc="_imgSrcFromPCRadio",Sc="_imgSrcFromWebRadio",Tc="_imgUrlTextError",Uc="_imgUrlTextInput",Vc="_picImg",Wc="a",Xc="a:link, a:visited, a:active, a:hover { color: ",Yc="abort",Zc=
"absolute",$c="action",ad="action=",bd="additions text",cd="addnew",dd="ajaxAction",ed="allHolder",fd="alpha(opacity=1)",gd="animate",hd="anonNameField",id="anonUrlField",jd="application/x-www-form-urlencoded;charset=utf-8",kd="aria-",ld="aria-expanded",md="array",nd="arraybuffer",od="begin",pd="bgint",qd="bgresponse",rd="block",sd="blogID",td="blogger-clickTrap singleton-element",ud="blur",vd="body { color: ",wd="button",xd="call",yd="captcha-error",zd="center",Ad="change",Bd="checkbox",Cd="checked",
Dd="chooseWidget",Ed="class",Fd="click",Gd="commentBody-err",Hd="commentBodyField",Id="commentDash",Jd="commentForm",Kd="commentSubscriptionForm",Ld="compact",p="complete",Md="config",Nd="configure",Od="content-type",Pd="data-",Qd="default",Rd="delete",Sd="destroy",Td="disabled",Ud="display",Vd="displayModeFull",Wd="displayModeLayout",Xd="displayModeNone",Yd="displayModeSnippet",q="div",Zd="downloadprogress",$d="edit-link",ae="editButton",be="editlink",ce="encodedIds",de="encodedSelectedId",ee="end",
fe="error",ge="error-details",he="errorbox-bad errormsg",ie="errorbox-good",je="errormessage_",ke="event",le="expanded",me="expected object of type SafeStyleSheet, got '",ne="expression(this.parentNode.clientHeight)",oe="false",pe="file",qe="finish",re="focus",se="for",te="form",t="function",ue="g",ve="genericOpenIdDialogErrorHolder",we="genericOpenIdIdentityHolder",xe="goog-zippy-collapsed",ye="goog-zippy-content",ze="goog-zippy-expanded",Ae="goog-zippy-header",Be="goog.dom.setTextContent expects a non-null value for node",
Ce="goog.net.EventType.PROGRESS is of the same type as raw XHR progress.",De="hidden",Ee="href",Fe="http",Ge="http://",He="http://openid.aol.com/{username}",Ie="http://{username}.livejournal.com",Je="http://{username}.wordpress.com",Ke="https://profile.typepad.com/{username}",Le="id",Me="id-error",Ne="identity-type-",Oe="identityControlsHolder",Pe="identityHolder",Qe="identityMenu",Re="iemode",Se="image",Te="imageUpload.do",Ue="img",Ve="infinite loop",We="inline",Xe="input",Ye="keydown",Ze="keypress",
$e="keyup",af="layout-title",bf="layout-widget-description",cf="layout-widget-state ",df="layout-widget-title",ef="main-error",ff="main-error-holder",gf="main-status",hf="main-status-holder",jf="mouseout",kf="mouseover",lf="mozResponseArrayBuffer",mf="multipart/form-data",nf="nameUrlDialogErrorHolder",of="nameUrlIdentityHolder",pf="native code",qf="no type",rf="no widget for ",u="none",sf="not-visible",tf="null",uf="number",vf="o",wf="object",xf="off",yf="on",zf="oninput",Af="onprogress",Bf="openIdDialogErrorHolder",
Cf="openIdIdentityHolder",Df="openIdUriDisplayPrefix",Ef="openIdUriDisplaySuffix",Ff="openIdUriDisplayUsername",Gf="openIdUriField",Hf="openIdUserNameField",If="openIdUsernameLabel",Jf="option",Kf="overflow:hidden",Lf="page",Mf="pageID",Nf="play",Of="polyfill",Pf="postCommentPreview",Qf="postCommentSubmit",Rf="previewHolder",Sf="previewMode",Tf="progress",Uf="px",Vf="radio",Wf="ready",Xf="readystatechange",Yf="reset",Zf="response",$f="responseType=js",ag="resume",bg="role",cg="rotate(-45deg)",dg=
"sectionId",eg="sectionWidth",fg="security_token",gg="select",hg="select-multiple",ig="select-one",jg="set-comment-editor-height ",kg="settingsButton",lg="showPreview",mg="singleton-element",ng="span",og="splice",pg="status-message",qg="status-message-inner",rg="stop",sg="string",tg="style",ug="submit",vg="subscribeButtonHolder",wg="success",xg="tab",yg="text",zg="text/javascript",Ag="textContent",Bg="timeout",Cg="title",Dg="toggle",Eg="true",Fg="type_error:SafeStyleSheet",Gg="uploadprogress",Hg=
"use",Ig="username",Jg="var ",Kg="vertical",Lg="viewBox",Mg="visible",Ng="white",Og="widget-content",Pg="widget-wrap1",Qg="widget-wrap2",Rg="widget-wrap3",Sg="widgetId=",Tg="widgetType",Ug="widgetType=",Vg="width=570,height=600,left=75,top=20,resizable=yes,scrollbars=yes",Wg="window",Xg="withCredentials",Yg="xlink:href",Zg="{username}",$g="}",v,ah=ah||{},w=this,x=function(a){return void 0!==a},y=function(a,b,c){a=a.split(Qa);c=c||w;a[0]in c||!c.execScript||c.execScript(Jg+a[0]);for(var d;a.length&&
(d=a.shift());)!a.length&&x(b)?c[d]=b:c=c[d]?c[d]:c[d]={}},bh=function(){},ch=function(a){a.Zf=function(){return a.Pd?a.Pd:a.Pd=new a}},dh=function(a){var b=typeof a;if(b==wf)if(a){if(a instanceof Array)return md;if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c==Hc)return wf;if(c==Fc||typeof a.length==uf&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(og))return md;if(c==Gc||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable(xd))return t}else return tf;else if(b==t&&"undefined"==typeof a.call)return wf;return b},z=function(a){return dh(a)==md},eh=function(a){var b=dh(a);return b==md||b==wf&&typeof a.length==uf},A=function(a){return typeof a==sg},fh=function(a){return typeof a==uf},gh=function(a){return dh(a)==t},hh=function(a){var b=typeof a;return b==wf&&null!=a||b==t},ih="closure_uid_"+(1E9*Math.random()>>>0),jh=0,kh=function(a,b,c){return a.call.apply(a.bind,arguments)},lh=function(a,b,c){if(!a)throw Error();
if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},B=function(a,b,c){B=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf(pf)?kh:lh;return B.apply(null,arguments)},mh=Date.now||function(){return+new Date},C=function(a,b){function c(){}c.prototype=b.prototype;a.h=b.prototype;a.prototype=new c;a.prototype.constructor=
a;a.pj=function(a,c,g){for(var k=Array(arguments.length-2),m=2;m<arguments.length;m++)k[m-2]=arguments[m];return b.prototype[c].apply(a,k)}};var nh=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,nh);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};C(nh,Error);nh.prototype.name="CustomError";var oh;var ph=function(a,b){for(var c=a.split(ta),d=e,f=Array.prototype.slice.call(arguments,1);f.length&&1<c.length;)d+=c.shift()+f.shift();return d+c.join(ta)},qh=function(a){return a.replace(/(\r\n|\r|\n)+/g,h)},rh=function(a){return a.replace(/\xa0|[ \t]+/g,h)},sh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,e)},Ah=function(a,b){if(b)a=a.replace(th,ya).replace(uh,Ba).replace(vh,Aa).replace(wh,Da).replace(xh,wa).replace(yh,va);else{if(!zh.test(a))return a;
-1!=a.indexOf(l)&&(a=a.replace(th,ya));-1!=a.indexOf(tb)&&(a=a.replace(uh,Ba));-1!=a.indexOf(ub)&&(a=a.replace(vh,Aa));-1!=a.indexOf(la)&&(a=a.replace(wh,Da));-1!=a.indexOf(Ha)&&(a=a.replace(xh,wa));-1!=a.indexOf(aa)&&(a=a.replace(yh,va))}return a},th=/&/g,uh=/</g,vh=/>/g,wh=/"/g,xh=/'/g,yh=/\x00/g,zh=/[\x00&<>"']/,Bh=function(a,b){return a<b?-1:a>b?1:0};var Ch=function(a,b){b.unshift(a);nh.call(this,ph.apply(null,b));b.shift()};C(Ch,nh);Ch.prototype.name="AssertionError";
var Dh=function(a,b,c,d){var f=Fb;if(c)var f=f+(qb+c),g=d;else a&&(f+=qb+a,g=b);throw new Ch(e+f,g||[]);},D=function(a,b,c){a||Dh(e,null,b,Array.prototype.slice.call(arguments,2));return a},Eh=function(a,b){throw new Ch("Failure"+(a?qb+a:e),Array.prototype.slice.call(arguments,1));},E=function(a,b,c){fh(a)||Dh(Ob,[dh(a),a],b,Array.prototype.slice.call(arguments,2));return a},Fh=function(a,b,c){A(a)||Dh(Pb,[dh(a),a],b,Array.prototype.slice.call(arguments,2));return a};var Gh=Array.prototype.indexOf?function(a,b,c){D(null!=a.length);return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(A(a))return A(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Hh=Array.prototype.lastIndexOf?function(a,b,c){D(null!=a.length);return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(A(a))return A(b)&&1==
b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1},Ih=Array.prototype.forEach?function(a,b,c){D(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=A(a)?a.split(e):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},Jh=Array.prototype.filter?function(a,b,c){D(null!=a.length);return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,k=A(a)?a.split(e):a,m=0;m<d;m++)if(m in k){var r=k[m];b.call(c,r,m,a)&&(f[g++]=
r)}return f},Kh=Array.prototype.some?function(a,b,c){D(null!=a.length);return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=A(a)?a.split(e):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1},Lh=function(a,b,c){a:{for(var d=a.length,f=A(a)?a.split(e):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a)){b=g;break a}b=-1}return 0>b?null:A(a)?a.charAt(b):a[b]},F=function(a,b){return 0<=Gh(a,b)},Mh=function(a){if(!z(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0},
Oh=function(a,b){var c=Gh(a,b),d;(d=0<=c)&&Nh(a,c);return d},Nh=function(a,b){D(null!=a.length);return 1==Array.prototype.splice.call(a,b,1).length},Ph=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)},Qh=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Rh=function(a,b,c){D(null!=a.length);return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Sh=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Th=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Uh=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Vh=function(a,b){return null!==a&&b in a},Wh=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1},Xh=function(a){for(var b in a)return!1;return!0},Yh="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Zh=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=
arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<Yh.length;g++)c=Yh[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var G;a:{var $h=w.navigator;if($h){var ai=$h.userAgent;if(ai){G=ai;break a}}G=e};var ci=function(){this.Ec=e;this.hf=bi},bi={};ci.prototype.toString=function(){return sc+this.Ec+$g};ci.prototype.tg=function(a){this.Ec=a;return this};var ei=function(a){di();return(new ci).tg(a)},di=bh;var fi=function(a,b){this.width=a;this.height=b};v=fi.prototype;v.clone=function(){return new fi(this.width,this.height)};v.toString=function(){return Ja+this.width+ka+this.height+La};v.Ef=function(){return this.width*this.height};v.isEmpty=function(){return!this.Ef()};v.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var gi=-1!=G.indexOf("Opera")||-1!=G.indexOf("OPR"),H=-1!=G.indexOf("Trident")||-1!=G.indexOf("MSIE"),hi=-1!=G.indexOf("Edge"),ii=-1!=G.indexOf("Gecko")&&!(-1!=G.toLowerCase().indexOf("webkit")&&-1==G.indexOf("Edge"))&&!(-1!=G.indexOf("Trident")||-1!=G.indexOf("MSIE"))&&-1==G.indexOf("Edge"),ji=-1!=G.toLowerCase().indexOf("webkit")&&-1==G.indexOf("Edge"),ki=function(){var a=w.document;return a?a.documentMode:void 0},li;
a:{var mi=e,ni=function(){var a=G;if(ii)return/rv\:([^\);]+)(\)|;)/.exec(a);if(hi)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ji)return/WebKit\/(\S+)/.exec(a);if(gi)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ni&&(mi=ni?ni[1]:e);if(H){var oi=ki();if(null!=oi&&oi>parseFloat(mi)){li=String(oi);break a}}li=mi}
var pi=li,qi={},I=function(a){var b;if(!(b=qi[a])){b=0;for(var c=sh(String(pi)).split(Qa),d=sh(String(a)).split(Qa),f=Math.max(c.length,d.length),g=0;0==b&&g<f;g++){var k=c[g]||e,m=d[g]||e,r=RegExp(Ka,ue),ua=RegExp(Ka,ue);do{var Y=r.exec(k)||[e,e,e],Sa=ua.exec(m)||[e,e,e];if(0==Y[0].length&&0==Sa[0].length)break;b=Bh(0==Y[1].length?0:parseInt(Y[1],10),0==Sa[1].length?0:parseInt(Sa[1],10))||Bh(0==Y[2].length,0==Sa[2].length)||Bh(Y[2],Sa[2])}while(0==b)}b=qi[a]=0<=b}return b},ri=w.document,si=ri&&H?
ki()||(ri.compatMode==Hb?parseInt(pi,10):5):void 0;var ti=!H||9<=Number(si);!ii&&!H||H&&9<=Number(si)||ii&&I("1.9.1");H&&I("9");var wi=function(a){return a?new ui(vi(a)):oh||(oh=new ui)},J=function(a){return A(a)?document.getElementById(a):a},yi=function(a,b){Sh(b,function(b,d){d==tg?a.style.cssText=b:d==Ed?a.className=b:d==se?a.htmlFor=b:xi.hasOwnProperty(d)?a.setAttribute(xi[d],b):0==d.lastIndexOf(kd,0)||0==d.lastIndexOf(Pd,0)?a.setAttribute(d,b):a[d]=b})},xi={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:bg,rowspan:"rowSpan",
type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Ai=function(a,b,c){return zi(document,arguments)},zi=function(a,b){var c=b[0],d=b[1];if(!ti&&d&&(d.name||d.type)){c=[tb,c];d.name&&c.push(ea,Ah(d.name),la);if(d.type){c.push(ia,Ah(d.type),la);var f={};Zh(f,d);delete f.type;d=f}c.push(ub);c=c.join(e)}c=a.createElement(c);d&&(A(d)?c.className=d:z(d)?c.className=d.join(h):yi(c,d));2<b.length&&Bi(a,c,b,2);return c},Bi=function(a,b,c,d){function f(c){c&&b.appendChild(A(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var g=c[d];!eh(g)||hh(g)&&0<g.nodeType?f(g):Ih(Ci(g)?Qh(g):g,f)}},Di=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},vi=function(a){D(a,kc);return 9==a.nodeType?a:a.ownerDocument||a.document},Ci=function(a){if(a&&typeof a.length==uf){if(hh(a))return typeof a.item==t||typeof a.item==sg;if(gh(a))return typeof a.item==t}return!1},ui=function(a){this.ta=a||w.document||document};v=ui.prototype;v.rb=function(a){return A(a)?this.ta.getElementById(a):a};
v.Ad=function(a,b,c){c=c||this.ta;a=a&&a!=Ma?a.toUpperCase():e;if(c.querySelectorAll&&c.querySelector&&(a||b))b=c.querySelectorAll(a+(b?Qa+b:e));else if(b&&c.getElementsByClassName)if(c=c.getElementsByClassName(b),a){for(var d={},f=0,g=0,k;k=c[g];g++)a==k.nodeName&&(d[f++]=k);d.length=f;b=d}else b=c;else if(c=c.getElementsByTagName(a||Ma),b){d={};for(g=f=0;k=c[g];g++)a=k.className,typeof a.split==t&&F(a.split(/\s+/),b)&&(d[f++]=k);d.length=f;b=d}else b=c;return b};
v.dc=function(a,b,c){return zi(this.ta,arguments)};v.createElement=function(a){return this.ta.createElement(a)};v.createTextNode=function(a){return this.ta.createTextNode(String(a))};v.appendChild=function(a,b){a.appendChild(b)};v.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var K=function(){this.sa=this.sa;this.Hb=this.Hb};K.prototype.sa=!1;K.prototype.la=function(){this.sa||(this.sa=!0,this.l())};K.prototype.l=function(){if(this.Hb)for(;this.Hb.length;)this.Hb.shift()()};var Ei=function(a){a&&typeof a.la==t&&a.la()};var L=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.pa=!1;this.re=!0};L.prototype.stopPropagation=function(){this.pa=!0};L.prototype.preventDefault=function(){this.defaultPrevented=!0;this.re=!1};var Fi=function(a){Fi[h](a);return a};Fi[h]=bh;var Gi=!H||9<=Number(si),Hi=H&&!I("9");!ji||I("528");ii&&I("1.9b")||H&&I("8")||gi&&I("9.5")||ji&&I("528");ii&&!I("8")||H&&I("9");var M=function(a,b){L.call(this,a?a.type:e);this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.La=this.state=null;a&&this.Nd(a,b)};C(M,L);
M.prototype.Nd=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;var f=a.relatedTarget;if(f){if(ii){var g;a:{try{Fi(f.nodeName);g=!0;break a}catch(k){}g=!1}g||(f=null)}}else c==kf?f=a.fromElement:c==jf&&(f=a.toElement);this.relatedTarget=f;null===d?(this.offsetX=ji||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=ji||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=
void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c==Ze?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.La=a;a.defaultPrevented&&this.preventDefault()};
M.prototype.stopPropagation=function(){M.h.stopPropagation.call(this);this.La.stopPropagation?this.La.stopPropagation():this.La.cancelBubble=!0};M.prototype.preventDefault=function(){M.h.preventDefault.call(this);var a=this.La;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Hi)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Ii="closure_listenable_"+(1E6*Math.random()|0),Ji=function(a){return!(!a||!a[Ii])},Ki=0;var Li=function(a,b,c,d,f,g){this.listener=a;this.proxy=b;this.src=c;this.type=d;this.ib=!!f;this.vb=g;this.key=++Ki;this.Ba=this.hb=!1};Li.prototype.Fb=function(){this.Ba=!0;this.vb=this.src=this.proxy=this.listener=null};var Mi=function(a){this.src=a;this.o={};this.ab=0};v=Mi.prototype;v.add=function(a,b,c,d,f){var g=a.toString();a=this.o[g];a||(a=this.o[g]=[],this.ab++);var k=Ni(a,b,d,f);-1<k?(b=a[k],c||(b.hb=!1)):(b=new Li(b,null,this.src,g,!!d,f),b.hb=c,a.push(b));return b};v.remove=function(a,b,c,d){a=a.toString();if(!(a in this.o))return!1;var f=this.o[a];b=Ni(f,b,c,d);return-1<b?(f[b].Fb(),Nh(f,b),0==f.length&&(delete this.o[a],this.ab--),!0):!1};
v.ne=function(a){var b=a.type;if(!(b in this.o))return!1;var c=Oh(this.o[b],a);c&&(a.Fb(),0==this.o[b].length&&(delete this.o[b],this.ab--));return c};v.Jb=function(a){a=a&&a.toString();var b=0,c;for(c in this.o)if(!a||c==a){for(var d=this.o[c],f=0;f<d.length;f++)++b,d[f].Fb();delete this.o[c];this.ab--}return b};v.Ma=function(a,b,c,d){a=this.o[a.toString()];var f=-1;a&&(f=Ni(a,b,c,d));return-1<f?a[f]:null};
var Ni=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.Ba&&g.listener==b&&g.ib==!!c&&g.vb==d)return f}return-1};var Oi="closure_lm_"+(1E6*Math.random()|0),Pi={},Qi=0,N=function(a,b,c,d,f){if(z(b)){for(var g=0;g<b.length;g++)N(a,b[g],c,d,f);return null}c=Ri(c);return Ji(a)?a.Aa(b,c,d,f):Si(a,b,c,!1,d,f)},Si=function(a,b,c,d,f,g){if(!b)throw Error("Invalid event type");var k=!!f,m=Ti(a);m||(a[Oi]=m=new Mi(a));c=m.add(b,c,d,f,g);if(c.proxy)return c;d=Ui();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,k);else if(a.attachEvent)a.attachEvent(Vi(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");
Qi++;return c},Ui=function(){var a=Wi,b=Gi?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Xi=function(a,b,c,d,f){if(z(b)){for(var g=0;g<b.length;g++)Xi(a,b[g],c,d,f);return null}c=Ri(c);return Ji(a)?a.uc(b,c,d,f):Si(a,b,c,!0,d,f)},Yi=function(a,b,c,d,f){if(z(b)){for(var g=0;g<b.length;g++)Yi(a,b[g],c,d,f);return null}c=Ri(c);if(Ji(a))return a.Ob(b,c,d,f);if(!a)return!1;if(a=Ti(a))if(b=a.Ma(b,c,!!d,f))return Zi(b);return!1},Zi=function(a){if(fh(a)||
!a||a.Ba)return!1;var b=a.src;if(Ji(b))return b.Je(a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.ib):b.detachEvent&&b.detachEvent(Vi(c),d);Qi--;(c=Ti(b))?(c.ne(a),0==c.ab&&(c.src=null,b[Oi]=null)):a.Fb();return!0},$i=function(a,b){if(!a)return 0;if(Ji(a))return a.me(b);var c=Ti(a);if(!c)return 0;var d=0,f=b&&b.toString(),g;for(g in c.o)if(!f||g==f)for(var k=c.o[g].concat(),m=0;m<k.length;++m)Zi(k[m])&&++d;return d},Vi=function(a){return a in Pi?Pi[a]:Pi[a]=yf+a},bj=function(a,
b,c,d){var f=!0;if(a=Ti(a))if(b=a.o[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.ib==c&&!g.Ba&&(g=aj(g,d),f=f&&!1!==g)}return f},aj=function(a,b){var c=a.listener,d=a.vb||a.src;a.hb&&Zi(a);return c.call(d,b)},Wi=function(a,b){if(a.Ba)return!0;if(!Gi){var c;if(!(c=b))a:{c=[Wg,ke];for(var d=w,f;f=c.shift();)if(null!=d[f])d=d[f];else{c=null;break a}c=d}f=c;c=new M(f,this);d=!0;if(!(0>f.keyCode||void 0!=f.returnValue)){a:{var g=!1;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(r){g=
!0}if(g||void 0==f.returnValue)f.returnValue=!0}f=[];for(g=c.currentTarget;g;g=g.parentNode)f.push(g);for(var g=a.type,k=f.length-1;!c.pa&&0<=k;k--){c.currentTarget=f[k];var m=bj(f[k],g,!0,c),d=d&&m}for(k=0;!c.pa&&k<f.length;k++)c.currentTarget=f[k],m=bj(f[k],g,!1,c),d=d&&m}return d}return aj(a,new M(b,this))},Ti=function(a){a=a[Oi];return a instanceof Mi?a:null},cj="__closure_events_fn_"+(1E9*Math.random()>>>0),Ri=function(a){D(a,Xb);if(gh(a))return a;D(a.handleEvent,Db);a[cj]||(a[cj]=function(b){return a.handleEvent(b)});
return a[cj]};var O=function(){K.call(this);this.V=new Mi(this);this.xf=this;this.Bc=null};C(O,K);O.prototype[Ii]=!0;v=O.prototype;v.addEventListener=function(a,b,c,d){N(this,a,b,c,d)};v.removeEventListener=function(a,b,c,d){Yi(this,a,b,c,d)};
v.dispatchEvent=function(a){this.gd();var b,c=this.Bc;if(c){b=[];for(var d=1;c;c=c.Bc)b.push(c),D(1E3>++d,Ve)}c=this.xf;d=a.type||a;if(A(a))a=new L(a,c);else if(a instanceof L)a.target=a.target||c;else{var f=a;a=new L(d,c);Zh(a,f)}var f=!0,g;if(b)for(var k=b.length-1;!a.pa&&0<=k;k--)g=a.currentTarget=b[k],f=g.pb(d,!0,a)&&f;a.pa||(g=a.currentTarget=c,f=g.pb(d,!0,a)&&f,a.pa||(f=g.pb(d,!1,a)&&f));if(b)for(k=0;!a.pa&&k<b.length;k++)g=a.currentTarget=b[k],f=g.pb(d,!1,a)&&f;return f};
v.l=function(){O.h.l.call(this);this.me();this.Bc=null};v.Aa=function(a,b,c,d){this.gd();return this.V.add(String(a),b,!1,c,d)};v.uc=function(a,b,c,d){return this.V.add(String(a),b,!0,c,d)};v.Ob=function(a,b,c,d){return this.V.remove(String(a),b,c,d)};v.Je=function(a){return this.V.ne(a)};v.me=function(a){return this.V?this.V.Jb(a):0};
v.pb=function(a,b,c){a=this.V.o[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,f=0;f<a.length;++f){var g=a[f];if(g&&!g.Ba&&g.ib==b){var k=g.listener,m=g.vb||g.src;g.hb&&this.Je(g);d=!1!==k.call(m,c)&&d}}return d&&0!=c.re};v.Ma=function(a,b,c,d){return this.V.Ma(String(a),b,c,d)};v.gd=function(){D(this.V,Nb)};var dj=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,xb).replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,Ic).replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e)))try{return eval(Ja+a+La)}catch(b){}throw Error("Invalid JSON string: "+a);};var ej=function(a){return a};var fj="StopIteration"in w?w.StopIteration:{message:"StopIteration",stack:e},gj=function(){};gj.prototype.next=function(){throw fj;};gj.prototype.Yb=function(){return this};var hj=function(a,b){this.j={};this.c=[];this.bb=this.b=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};v=hj.prototype;v.s=function(){return this.b};v.u=function(){this.lb();for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};v.K=function(){this.lb();return this.c.concat()};v.ka=function(a){return ij(this.j,a)};v.isEmpty=function(){return 0==this.b};
v.clear=function(){this.j={};this.bb=this.b=this.c.length=0};v.remove=function(a){return ij(this.j,a)?(delete this.j[a],this.b--,this.bb++,this.c.length>2*this.b&&this.lb(),!0):!1};v.lb=function(){if(this.b!=this.c.length){for(var a=0,b=0;a<this.c.length;){var c=this.c[a];ij(this.j,c)&&(this.c[b++]=c);a++}this.c.length=b}if(this.b!=this.c.length){for(var d={},b=a=0;a<this.c.length;)c=this.c[a],ij(d,c)||(this.c[b++]=c,d[c]=1),a++;this.c.length=b}};
v.get=function(a,b){return ij(this.j,a)?this.j[a]:b};v.set=function(a,b){ij(this.j,a)||(this.b++,this.c.push(a),this.bb++);this.j[a]=b};v.addAll=function(a){var b;a instanceof hj?(b=a.K(),a=a.u()):(b=Uh(a),a=Th(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};v.forEach=function(a,b){for(var c=this.K(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};v.clone=function(){return new hj(this)};
v.Yb=function(a){this.lb();var b=0,c=this.bb,d=this,f=new gj;f.next=function(){if(c!=d.bb)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw fj;var f=d.c[b++];return a?f:d.j[f]};return f};var ij=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var jj=function(a){if(a.u&&typeof a.u==t)return a.u();if(A(a))return a.split(e);if(eh(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Th(a)},kj=function(a,b,c){if(a.forEach&&typeof a.forEach==t)a.forEach(b,c);else if(eh(a)||A(a))Ih(a,b,c);else{var d;if(a.K&&typeof a.K==t)d=a.K();else if(a.u&&typeof a.u==t)d=void 0;else if(eh(a)||A(a)){d=[];for(var f=a.length,g=0;g<f;g++)d.push(g)}else d=Uh(a);for(var f=jj(a),g=f.length,k=0;k<g;k++)b.call(c,f[k],d&&d[k],a)}};var lj=function(a){this.j=new hj;a&&this.addAll(a)},mj=function(a){var b=typeof a;return b==wf&&a||b==t?vf+(a[ih]||(a[ih]=++jh)):b.substr(0,1)+a};v=lj.prototype;v.s=function(){return this.j.s()};v.add=function(a){this.j.set(mj(a),a)};v.addAll=function(a){a=jj(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};v.Jb=function(a){a=jj(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};v.remove=function(a){return this.j.remove(mj(a))};v.clear=function(){this.j.clear()};v.isEmpty=function(){return this.j.isEmpty()};
v.contains=function(a){return this.j.ka(mj(a))};v.u=function(){return this.j.u()};v.clone=function(){return new lj(this)};v.Yb=function(){return this.j.Yb(!1)};var nj=function(a,b,c){if(gh(a))c&&(a=B(a,c));else if(a&&typeof a.handleEvent==t)a=B(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:w.setTimeout(a,b||0)};var oj=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,pj=function(a,b){if(a)for(var c=a.split(l),d=0;d<c.length;d++){var f=c[d].indexOf(n),g=null,k=null;0<=f?(g=c[d].substring(0,f),k=c[d].substring(f+1)):g=c[d];b(g,k?decodeURIComponent(k.replace(/\+/g,h)):e)}};var qj=function(){};qj.prototype.md=null;qj.prototype.Fd=function(){return this.md||(this.md=this.wg())};var rj,sj=function(){};C(sj,qj);sj.prototype.qd=function(){var a=this.Gd();return a?new ActiveXObject(a):new XMLHttpRequest};sj.prototype.wg=function(){var a={};this.Gd()&&(a[0]=!0,a[1]=!0);return a};
sj.prototype.Gd=function(){if(!this.Ld&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var a=[bc,ac,$b,dc],b=0;b<a.length;b++){var c=a[b];try{return new ActiveXObject(c),this.Ld=c}catch(d){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return this.Ld};rj=new sj;var P=function(a){O.call(this);this.headers=new hj;this.Tb=a||null;this.aa=!1;this.Sb=this.a=null;this.tc=e;this.za=0;this.na=this.qc=this.yb=this.ic=!1;this.qa=0;this.Nb=null;this.Ca=e;this.Nc=this.hh=this.Fa=!1};C(P,O);var tj=/^https?$/i,uj=[nc,"PUT"],vj=[],wj=function(a,b,c,d,f,g,k){var m=new P;vj.push(m);b&&m.Aa(p,b);m.uc(Wf,m.If);g&&m.Ic(g);k&&m.Jc(k);m.send(a,c,d,f);return m};v=P.prototype;v.If=function(){this.la();Oh(vj,this)};v.Ic=function(a){this.qa=Math.max(0,a)};
v.ph=function(a){this.Ca=a};v.Jc=function(a){this.Fa=a};
v.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request="+this.tc+"; newUri="+a);b=b?b.toUpperCase():Rb;this.tc=a;this.za=0;this.ic=!1;this.aa=!0;this.a=this.Mf();this.Sb=this.Tb?this.Tb.Fd():rj.Fd();this.a.onreadystatechange=B(this.he,this);this.hh&&Af in this.a&&(this.a.onprogress=B(function(a){this.fe(a,!0)},this),this.a.upload&&(this.a.upload.onprogress=B(this.fe,this)));try{this.qc=!0,this.a.open(b,String(a),!0),this.qc=!1}catch(g){this.yd(5,g);
return}a=c||e;var f=this.headers.clone();d&&kj(d,function(a,b){f.set(b,a)});d=Lh(f.K(),xj);c=w.FormData&&a instanceof w.FormData;!F(uj,b)||d||c||f.set(Lb,jd);f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Ca&&(this.a.responseType=this.Ca);Vh(this.a,Xg)&&(this.a.withCredentials=this.Fa);try{this.nd(),0<this.qa&&((this.Nc=yj(this.a))?(this.a.timeout=this.qa,this.a.ontimeout=B(this.He,this)):this.Nb=nj(this.He,this.qa,this)),this.yb=!0,this.a.send(a),this.yb=!1}catch(g){this.yd(5,g)}};
var yj=function(a){return H&&I(9)&&fh(a.timeout)&&x(a.ontimeout)},xj=function(a){return Od==a.toLowerCase()};v=P.prototype;v.Mf=function(){return this.Tb?this.Tb.qd():rj.qd()};v.He=function(){"undefined"!=typeof ah&&this.a&&(this.za=8,this.dispatchEvent(Bg),this.abort(8))};v.yd=function(a){this.aa=!1;this.a&&(this.na=!0,this.a.abort(),this.na=!1);this.za=a;this.vd();this.kb()};v.vd=function(){this.ic||(this.ic=!0,this.dispatchEvent(p),this.dispatchEvent(fe))};
v.abort=function(a){this.a&&this.aa&&(this.aa=!1,this.na=!0,this.a.abort(),this.na=!1,this.za=a||7,this.dispatchEvent(p),this.dispatchEvent(Yc),this.kb())};v.l=function(){this.a&&(this.aa&&(this.aa=!1,this.na=!0,this.a.abort(),this.na=!1),this.kb(!0));P.h.l.call(this)};v.he=function(){this.sa||(this.qc||this.yb||this.na?this.ge():this.ah())};v.ah=function(){this.ge()};
v.ge=function(){if(this.aa&&"undefined"!=typeof ah&&(!this.Sb[1]||4!=this.tb()||2!=this.getStatus()))if(this.yb&&4==this.tb())nj(this.he,0,this);else if(this.dispatchEvent(Xf),this.yg()){this.aa=!1;try{this.Sa()?(this.dispatchEvent(p),this.dispatchEvent(wg)):(this.za=6,this.vd())}finally{this.kb()}}};v.fe=function(a,b){D(a.type===Tf,Ce);this.dispatchEvent(zj(a,Tf));this.dispatchEvent(zj(a,b?Zd:Gg))};var zj=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}};
v=P.prototype;v.kb=function(a){if(this.a){this.nd();var b=this.a,c=this.Sb[0]?bh:null;this.Sb=this.a=null;a||this.dispatchEvent(Wf);try{b.onreadystatechange=c}catch(d){}}};v.nd=function(){this.a&&this.Nc&&(this.a.ontimeout=null);fh(this.Nb)&&(w.clearTimeout(this.Nb),this.Nb=null)};v.Ab=function(){return!!this.a};v.yg=function(){return 4==this.tb()};
v.Sa=function(){var a=this.getStatus(),b;a:switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:b=!0;break a;default:b=!1}return b||0===a&&!this.zg()};v.zg=function(){var a=String(this.tc).match(oj)[1]||null;!a&&w.self&&w.self.location&&(a=w.self.location.protocol,a=a.substr(0,a.length-1));return tj.test(a?a.toLowerCase():e)};v.tb=function(){return this.a?this.a.readyState:0};v.getStatus=function(){try{return 2<this.tb()?this.a.status:-1}catch(a){return-1}};
v.eg=function(){try{return this.a?this.a.responseText:e}catch(a){return e}};v.Hd=function(a){if(this.a){var b=this.a.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));return dj(b)}};v.dg=function(){try{if(!this.a)return null;if(Zf in this.a)return this.a.response;switch(this.Ca){case e:case yg:return this.a.responseText;case nd:if(lf in this.a)return this.a.mozResponseArrayBuffer}return null}catch(a){return null}};var Aj=function(){};Aj.prototype.R=function(){return fc};Aj.prototype.L=function(){return null};var Bj=function(a){this.label=a};C(Bj,Aj);Bj.prototype.A=function(){return this.label};var Q=function(a,b){this.label=b;this.value=a.R();this.X=a};C(Q,Aj);Q.prototype.A=function(){return this.label};Q.prototype.R=function(){return this.value};Q.prototype.encode=function(){return this.X.encode()+n};Q.prototype.L=function(){return new Cj(this)};var R=function(){};C(R,Aj);R.prototype.encode=function(){return encodeURIComponent(this.R())};R.prototype.L=function(){return null};var Dj=function(a){Q.call(this,a,a.A())};C(Dj,Q);var Ej=function(){};C(Ej,R);Ej.prototype.A=function(){return Eb};Ej.prototype.R=function(){return Ab};Ej.prototype.decode=function(){return new Dj(this)};var Fj=function(a,b){this.mb=this.Oc=this.Da=e;this.Ib=null;this.qb=this.je=e;this.G=this.Ag=!1;var c;a instanceof Fj?(this.G=x(b)?b:a.G,this.Be(a.Da),this.Fe(a.Oc),this.ve(a.mb),this.ze(a.Ib),this.setPath(a.getPath()),this.Ae(a.fa.clone()),this.xe(a.qb)):a&&(c=String(a).match(oj))?(this.G=!!b,this.Be(c[1]||e,!0),this.Fe(c[2]||e,!0),this.ve(c[3]||e,!0),this.ze(c[4]),this.setPath(c[5]||e,!0),this.Ae(c[6]||e,!0),this.xe(c[7]||e,!0)):(this.G=!!b,this.fa=new Gj(null,null,this.G))};v=Fj.prototype;
v.toString=function(){var a=[],b=this.Da;b&&a.push(Hj(b,Ij,!0),pb);var c=this.mb;if(c||b==pe)a.push(Za),(b=this.Oc)&&a.push(Hj(b,Ij,!0),xb),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,ra)),c=this.Ib,null!=c&&a.push(pb,String(c));if(c=this.getPath())this.og()&&c.charAt(0)!=Ya&&a.push(Ya),a.push(Hj(c,c.charAt(0)==Ya?Jj:Kj,!0));(c=this.Xf())&&a.push(vb,c);(c=this.qb)&&a.push(na,Hj(c,Lj));return a.join(e)};v.clone=function(){return new Fj(this)};
v.Be=function(a,b){this.da();if(this.Da=b?Mj(a,!0):a)this.Da=this.Da.replace(/:$/,e);return this};v.Fe=function(a,b){this.da();this.Oc=b?Mj(a):a;return this};v.ve=function(a,b){this.da();this.mb=b?Mj(a,!0):a;return this};v.og=function(){return!!this.mb};v.ze=function(a){this.da();if(a){a=Number(a);if(isNaN(a)||0>a)throw Error("Bad port number "+a);this.Ib=a}else this.Ib=null;return this};v.getPath=function(){return this.je};v.setPath=function(a,b){this.da();this.je=b?Mj(a,!0):a;return this};
v.Ae=function(a,b){this.da();a instanceof Gj?(this.fa=a,this.fa.Hc(this.G)):(b||(a=Hj(a,Nj)),this.fa=new Gj(a,null,this.G));return this};v.Xf=function(){return this.fa.toString()};v.Mb=function(a,b){this.da();this.fa.set(a,b);return this};v.xe=function(a,b){this.da();this.qb=b?Mj(a):a;return this};v.da=function(){if(this.Ag)throw Error("Tried to modify a read-only Uri");};v.Hc=function(a){this.G=a;this.fa&&this.fa.Hc(a);return this};
var Mj=function(a,b){return a?b?decodeURI(a.replace(/%25/g,sa)):decodeURIComponent(a):e},Hj=function(a,b,c){return A(a)?(a=encodeURI(a).replace(b,Oj),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,ra)),a):null},Oj=function(a){a=a.charCodeAt(0);return qa+(a>>4&15).toString(16)+(a&15).toString(16)},Ij=/[#\/\?@]/g,Kj=/[\#\?:]/g,Jj=/[\#\?]/g,Nj=/[\#\?@]/g,Lj=/#/g,Gj=function(a,b,c){this.b=this.g=null;this.ca=a||null;this.G=!!c};v=Gj.prototype;
v.U=function(){if(!this.g&&(this.g=new hj,this.b=0,this.ca)){var a=this;pj(this.ca,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,h)),c)})}};v.s=function(){this.U();return this.b};v.add=function(a,b){this.U();this.ya();a=this.va(a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.b=E(this.b)+1;return this};v.remove=function(a){this.U();a=this.va(a);return this.g.ka(a)?(this.ya(),this.b=E(this.b)-this.g.get(a).length,this.g.remove(a)):!1};
v.clear=function(){this.ya();this.g=null;this.b=0};v.isEmpty=function(){this.U();return 0==this.b};v.ka=function(a){this.U();a=this.va(a);return this.g.ka(a)};v.K=function(){this.U();for(var a=this.g.u(),b=this.g.K(),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};v.u=function(a){this.U();var b=[];if(A(a))this.ka(a)&&(b=Ph(b,this.g.get(this.va(a))));else{a=this.g.u();for(var c=0;c<a.length;c++)b=Ph(b,a[c])}return b};
v.set=function(a,b){this.U();this.ya();a=this.va(a);this.ka(a)&&(this.b=E(this.b)-this.g.get(a).length);this.g.set(a,[b]);this.b=E(this.b)+1;return this};v.get=function(a,b){var c=a?this.u(a):[];return 0<c.length?String(c[0]):b};v.setValues=function(a,b){this.remove(a);0<b.length&&(this.ya(),this.g.set(this.va(a),Qh(b)),this.b=E(this.b)+b.length)};
v.toString=function(){if(this.ca)return this.ca;if(!this.g)return e;for(var a=[],b=this.g.K(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(String(d)),d=this.u(d),g=0;g<d.length;g++){var k=f;d[g]!==e&&(k+=n+encodeURIComponent(String(d[g])));a.push(k)}return this.ca=a.join(l)};v.ya=function(){this.ca=null};v.clone=function(){var a=new Gj;a.ca=this.ca;this.g&&(a.g=this.g.clone(),a.b=this.b);return a};v.va=function(a){a=String(a);this.G&&(a=a.toLowerCase());return a};
v.Hc=function(a){a&&!this.G&&(this.U(),this.ya(),this.g.forEach(function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.setValues(d,a))},this));this.G=a};var Pj=e;var Qj=function(a){if(a.classList)return a.classList;a=a.className;return A(a)&&a.match(/\S+/g)||[]},Rj=function(a,b){return a.classList?a.classList.contains(b):F(Qj(a),b)},Sj=function(a,b){a.classList?a.classList.add(b):Rj(a,b)||(a.className+=0<a.className.length?h+b:b)},Tj=function(a,b){a.classList?a.classList.remove(b):Rj(a,b)&&(a.className=Jh(Qj(a),function(a){return a!=b}).join(h))};var Uj=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=ji&&!b&&!c;if((!x(b)||d)&&a.getBoundingClientRect){var f;a:{try{f=a.getBoundingClientRect()}catch(g){f={left:0,top:0,right:0,bottom:0};break a}H&&a.ownerDocument.body&&(a=a.ownerDocument,f.left-=a.documentElement.clientLeft+a.body.clientLeft,f.top-=a.documentElement.clientTop+a.body.clientTop)}return new fi(f.right-f.left,f.bottom-f.top)}return new fi(b,c)},Wj=function(a,b){var c=wi(b),d=null,f=c.ta;H&&f.createStyleSheet?(d=f.createStyleSheet(),
Vj(d,a)):(f=c.Ad(Ub)[0],f||(d=c.Ad(Gb)[0],f=c.dc(Ub),d.parentNode.insertBefore(f,d)),d=c.dc(rc),Vj(d,a),c.appendChild(f,d));return d},Vj=function(a,b){var c;b instanceof ci&&b.constructor===ci&&b.hf===bi?c=b.Ec:(Eh(me+b+Ia+dh(b)),c=Fg);if(H&&x(a.cssText))a.cssText=c;else if(D(null!=a,Be),Ag in a)a.textContent=c;else if(3==a.nodeType)a.data=c;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=c}else{Di(a);var d=vi(a);a.appendChild(d.createTextNode(String(c)))}};/*

 CC0 1.0 Universal License
 Public Domain Dedication

 The person(s) who associated a work with this deed has dedicated the work to
 the public domain by waiving all of his or her rights to the work worldwide
 under copyright law, including all related and neighboring rights, to the
 extent allowed by law.

 You can copy, modify, distribute and perform the work, even for commercial
 purposes, all without asking permission.

 In no way are the patent or trademark rights of any person affected by CC0,
 nor are the rights that other persons may have in the work or in how the work
 is used, such as publicity or privacy rights.

 Unless expressly stated otherwise, the person(s) who associated a work with
 this deed makes no warranties about the work, and disclaims liability for all
 uses of the work, to the fullest extent permitted by applicable law.

 When using or citing the work, you should not imply endorsement by the author
 or the affirmer.

 This is a human-readable summary of the Legal Code (read the full text).
*/
var Xj=function(a){function b(a,b){if(b){var c=document.createDocumentFragment(),k=!a.getAttribute(Lg)&&b.getAttribute(Lg);k&&a.setAttribute(Lg,k);for(k=b.cloneNode(!0);k.childNodes.length;)c.appendChild(k.firstChild);a.appendChild(c)}}function c(a){a.onreadystatechange=function(){if(4===a.readyState){var c=a.wf;c||(c=a.wf=document.implementation.createHTMLDocument(e),c.body.innerHTML=a.responseText,a.ad={});a.bd.splice(0).map(function(g){var k=a.ad[g.id];k||(k=a.ad[g.id]=c.getElementById(g.id));
b(g.th,k)})}};a.onreadystatechange()}(function(a){function f(){for(var a=0;a<Y.length;){var d=Y[a],m=d.parentNode;if(m&&/svg/i.test(m.nodeName)){var r=d.getAttribute(Yg);if(g&&(!k.wh||k.wh(r,m,d)))if(m.removeChild(d),r=r.split(na),d=r.shift(),r=r.join(na),d.length){var ga=ua[d];ga||(ga=ua[d]=new XMLHttpRequest,ga.open(Rb,d),ga.send(),ga.bd=[]);ga.bd.push({th:m,id:r});c(ga)}else b(m,document.getElementById(r))}else++a}window.requestAnimationFrame&&window.requestAnimationFrame(f)||setTimeout(f,67)}
var g,k=Object(a);a=/\bTrident\/[567]\b|\bMSIE (?:9|10)\.0\b/;var m=/\bAppleWebKit\/(\d+)\b/,r=/\bEdge\/12\.(\d+)\b/;g=Of in k?k.rj:a.test(navigator.userAgent)||10547>(navigator.userAgent.match(r)||[])[1]||537>(navigator.userAgent.match(m)||[])[1];var ua={},Y=document.getElementsByTagName(Hg);g&&f()})(a)};var Yj=function(a){return/^[A-Za-z0-9]+$/.test(a)||/^#[0-9A-Fa-f]{3}$/.test(a)||/^#[0-9A-Fa-f]{6}$/.test(a)||/^rgb *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)||/^rgba *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)},Zj=function(a){a=a.split(Na);for(var b=0;b<a.length;b++){var c=a[b],c=sh(c);if(!(/^[- A-Za-z0-9]*$/.test(c)||/^"[- A-Za-z0-9]*"$/.test(c)||/^'[- A-Za-z0-9]*'$/.test(c)))return!1}return!0},ak=function(){if(window.parent&&window.parent.postMessage){var a=
document.getElementById(Rf),b=0;if(a){b:{b=vi(a);if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.display||b.getPropertyValue(Ud)||e;break b}b=e}if((b||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display)!=u)a=Uj(a);else{var b=a.style,c=b.display,d=b.visibility,f=b.position;b.visibility=De;b.position=Zc;b.display=We;a=Uj(a);b.display=c;b.position=f;b.visibility=d}b=a.height}b=Math.max(b,document.body.scrollHeight);window.parent.postMessage(jg+
(b||230)+Uf,Ma)}},bk=function(){var a=document.getElementById(Hd),b=document.getElementById(Qf),c=document.getElementById(Pf),d=function(){b&&(b.disabled=a.value==e);c&&(c.disabled=a.value==e)};a&&zf in a&&(d(null),N(a,Xe,d))},ck=function(a){var b=e;H&&(b+=Va);a=(new Fj(a)).qb;if(0!=a.length){a=decodeURIComponent(a);var c=dj(a);if(c&&c.color){a=rh(qh(c.color));var d=rh(qh(c.unvisitedLinkColor)),c=rh(qh(c.fontFamily));Yj(a)&&Yj(d)&&Zj(c)&&(b=b+(vd+a+rb+c+sb)+(Xc+d+sb))}}Wj(ei(b),void 0);setTimeout(ak,
100);var f=J(ed);if((b=J(Hd))&&f){var g=!1;N(b,re,function(){g||(g=!0,Tj(f,Ld),ak())})}Xj()};var S=function(a){a=J(a);var b=a.nodeName.toLowerCase();a.style.display=b==ng||b==Ue||b==Wc||b==Xe||b==gg?We:rd},T=function(a){J(a).style.display=u};var U=function(a,b,c){var d;c&&T(hf);switch(a){case 0:a=d=yd;break;case 1:a=d=Me;break;case 2:case 3:case 4:a=ef;d=ff;break;case 5:a=d=nf;break;case 6:a=d=Bf;break;case 7:a=d=ve;break;default:throw Error("internal error in show message");}c?(J(a).innerHTML=b,S(d),J(Hd).className=Gd):(Di(J(a)),T(d));ak()},dk=function(a){U(3,null,!1);J(gf).innerHTML=a;S(hf);ak()};var ek=function(){};ek.prototype.sh=function(){T(Qe);J(Hd).disabled=!0;J(Qf).disabled=!0};ek.prototype.pg=function(){S(Qe);J(Hd).disabled=!1;J(Qf).disabled=!1};var Cj=function(a){this.m=a};C(Cj,ek);v=Cj.prototype;v.oa=function(){return!1};v.ga=function(){if(!this.oa())throw Error("Trying to show a non-editable identity");this.sh();S(Pe)};v.Cb=function(){return!0};v.Kc=function(){if(!this.oa())throw Error("Trying to show edit button for a non-editable identity");S(ae)};v.Va=function(){};v.Ya=function(){};v.Z=function(){T(Pe);T(ae);T(kg);T(Id);T(vg);this.pg()};var fk=function(a){a=a.className;return A(a)&&a.match(/\S+/g)||[]},gk=function(a,b){for(var c=fk(a),d=Rh(arguments,1),f=c.length+d.length,g=c,k=0;k<d.length;k++)F(g,d[k])||g.push(d[k]);a.className=c.join(h);return c.length==f},ik=function(a,b){var c=fk(a),d=Rh(arguments,1),f=hk(c,d);a.className=f.join(h);return f.length==c.length-d.length},hk=function(a,b){return Jh(a,function(a){return!F(b,a)})};var lk=function(a){for(var b=[],c=jk,d=a.elements,f,g=0;f=d[g];g++)if(f.form==a&&!f.disabled&&f.tagName!=Qb){var k=f.name;switch(f.type.toLowerCase()){case pe:case ug:case Yf:case wd:break;case hg:f=kk(f);if(null!=f)for(var m,r=0;m=f[r];r++)c(b,k,m);break;default:m=kk(f),null!=m&&c(b,k,m)}}d=a.getElementsByTagName(Vb);for(g=0;f=d[g];g++)f.form==a&&f.type.toLowerCase()==Se&&(k=f.name,c(b,k,f.value),c(b,k+Wa,cb),c(b,k+Xa,cb));return b.join(l)},jk=function(a,b,c){a.push(encodeURIComponent(b)+n+encodeURIComponent(c))},
kk=function(a){var b=a.type;if(!x(b))return null;switch(b.toLowerCase()){case Bd:case Vf:return a.checked?a.value:null;case ig:return b=a.selectedIndex,0<=b?a.options[b].value:null;case hg:for(var b=[],c,d=0;c=a.options[d];d++)c.selected&&b.push(c.value);return b.length?b:null;default:return x(a.value)?a.value:null}};var mk=!1,nk=!1,ok=!1,pk=function(a,b){nk=a;ok=b;if(window.parent==window.top&&(a||b)){var c=J(vg);b?gk(c,Cd):ik(c,Cd);S(vg);J(dd).value=b?Ac:uc}else T(vg)};var rk=function(a,b){Q.call(this,new qk,a);this.Wf=b};C(rk,Q);rk.prototype.encode=function(){return this.X.encode()+n+this.label+n+this.Wf};rk.prototype.A=function(){return this.label+ca};rk.prototype.L=function(){return new sk(this)};var qk=function(){};C(qk,R);qk.prototype.A=function(){return e};qk.prototype.R=function(){return Ib};qk.prototype.decode=function(a){return new rk(a[1],a[2])};qk.prototype.L=function(){throw Error("internal error");};var sk=function(a){this.m=a};C(sk,Cj);
sk.prototype.Kc=function(){(nk||ok)&&S(vg)};var tk=function(a){Q.call(this,a,a.A())};C(tk,Q);var uk=function(){};C(uk,R);uk.prototype.A=function(){return Tb};uk.prototype.R=function(){return Sb};uk.prototype.decode=function(){return this.Ed()};uk.prototype.Ed=function(){return new tk(this)};var vk=function(a,b,c){Q.call(this,a,null);this.name=b;this.url=c};C(vk,Q);vk.prototype.A=function(){return this.name+ba+this.url+La};vk.prototype.encode=function(){return this.X.encode()+n+encodeURIComponent(this.name)+n+encodeURIComponent(this.url)};vk.prototype.L=function(){return new wk(this)};var xk=function(){};C(xk,R);xk.prototype.A=function(){return hc};xk.prototype.R=function(){return ec};xk.prototype.L=function(){return new wk(new vk(this,e,e))};
xk.prototype.decode=function(a){return new vk(this,a[1],a[2])};var wk=function(a){this.m=a};C(wk,Cj);v=wk.prototype;v.oa=function(){return!0};v.ga=function(){wk.h.ga.call(this);S(of)};v.Z=function(){wk.h.Z.call(this);T(of);U(5,null,!1);this.ye(e);this.Ee(e)};v.Va=function(){this.ye(this.m.name);this.Ee(this.m.url)};v.Ya=function(){wk.h.Ya.call(this);this.m.name=this.Dd();this.m.url=this.hg();this.Kc()};v.Cb=function(){return this.Dd()==e?(U(5,gc,!0),!1):!0};v.Dd=function(){return J(hd).value};
v.ye=function(a){J(hd).value=a};v.hg=function(){return J(id).value};v.Ee=function(a){J(id).value=a};var yk=function(){this.ma=[];this.Ua=[];this.Ia=[];this.Pa=[];this.i=this.D=null;this.H=[]};v=yk.prototype;v.zb=function(a,b,c,d){for(var f=0;f<this.H.length;f++)if(a==this.H[f])return d(a);d=a.encode();for(f=0;f<this.H.length;f++)if(this.H[f].encode()==d)return c(this.H[f]);return b(a)};v.vg=function(a){return this.zb(a,B(function(a){return this.H[this.H.length]=a},this),ej,ej)};v.Bb=function(a){function b(){return!1}return this.zb(a,function(){return!0},b,b)};
v.Ra=function(a){function b(){throw Error("item should have been unique");}this.zb(a,bh,b,b);return this.vg(a)};v.$b=function(a){return this.zb(a,B(function(a){this.H[this.H.length]=a;return this.ma[this.ma.length]=a},this),ej,ej)};v.$d=function(){for(var a=document.getElementById(Oe),b=Qj(a),c=0;c<b.length;c++)b[c].slice(0,14)==Ne&&Tj(a,b[c]);(b=this.Pa[J(Qe).selectedIndex])&&Sj(a,Ne+b.value)};v.ed=function(a){this.D=this.$b(a);this.Xa();this.Ha();this.gb(!1);return this.D};
v.ja=function(a){this.Ra(a);this.Ua[this.Ua.length]=a};v.Af=function(){var a=this.Ra(new uk);this.ja(a.Ed())};v.zf=function(){var a=new xk;this.Ra(a);this.Ia[this.Ia.length]=a};v.yf=function(){var a=this.Ra(new Ej),a=this.Ra(new Dj(a));this.Ia[this.Ia.length]=a};v.Ha=function(){var a=this.Pa[J(Qe).selectedIndex];a.constructor==Bj?this.Xa():(U(1,null,!1),this.i=a.L(),null!=this.i&&this.i.Va(),this.$d())};
v.gb=function(a){if(null!=this.i){var b=this.i.m;if(a&&this.i.oa()&&this.Bb(b)||!this.i.Cb())this.i.ga();else return this.i.Ya(),this.i.Z(),this.i.oa()&&this.i.Kc(),this.i=null,b}return null};v.kh=function(){this.Nf(J(ce).value);this.D=this.sd(J(de).value);null==this.D&&0<this.ma.length&&(this.D=this.ma[0]);null==this.D&&1==this.Ua.length&&(this.D=this.Ua[0]);this.Xa();null!=this.D&&(this.Ha(),this.gb(!1))};
v.fd=function(a,b){this.Pa[this.Pa.length]=b;var c=document.createElement(Jf);c.text=b.A();c.value=b.R();try{a.add(c,null)}catch(d){a.add(c)}this.D==b&&(c.selected=!0);return c};v.ac=function(a,b){for(var c=0;c<b.length;c++)this.fd(a,b[c])};v.Xa=function(){for(var a=J(Qe);0!=a.options.length;)a.remove(0);this.Pa=[];this.fd(a,new Bj(tc)).disabled=Td;this.ac(a,this.ma);this.ac(a,this.Ua);this.ac(a,this.Ia)};v.Tf=function(){for(var a=[],b=0;b<this.ma.length;b++)a[a.length]=this.ma[b].encode();return a.join(l)};
v.Nf=function(a){if(a!=e){a=a.split(l);for(var b=0;b<a.length;b++)this.sd(a[b])}};v.sd=function(a){if(a==e)return null;a=a.split(n);for(var b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);b=this.Vf(a[0]);return null!=b?(a=b.decode(a),this.$b(a)):null};v.Vf=function(a){for(var b=0;b<this.H.length;b++)if(this.H[b].encode()==a)return this.H[b];return null};v.Me=function(){var a=J(Hd).value;if(a==e)return U(2,Jb,!0),!1;if(1E6<a.length)return U(2,Kb,!0),!1;U(2,null,!1);return!0};
v.zc=function(){null!=this.i&&this.i.Z();this.Ha();var a=this.gb(!0);null!=a&&(this.D=a)};v.Rg=function(){var a=this.gb(!1);null!=a&&this.ed(a)};v.Qg=function(){null!=this.i&&(this.i.Z(),this.i=null);this.Xa();this.zc()};v.ie=function(){if(null==this.D||this.D.R()==fc)return U(1,oc,!0),!1;if(null!=this.i)return!1;J(ce).value=this.Tf();J(de).value=this.D.encode();return!0};v.Tg=function(){this.D&&(this.Ha(),this.i.ga())};v.Zg=function(){this.Me()&&this.ie()&&this.wd(!1)};
v.$g=function(){this.Me()&&this.ie()&&this.wd(!0)};v.wd=function(a){J(lg).value=a?Eg:oe;this.Ha();a=J(Jd);a.onsubmit();a.submit()};var zk=function(a,b,c,d){this.Of=a;this.Le=b;this.name=c;this.vh=d};C(zk,R);v=zk.prototype;v.A=function(){return this.name};v.encode=function(){return encodeURIComponent(this.Of)};v.Jf=function(a){return this.Le.replace(/{username}/,encodeURIComponent(a))};v.gg=function(){return this.Le.split(Zg)};v.L=function(){return new Ak(new Bk(this,e,e))};v.decode=function(a){return new Bk(this,a[1],a[2])};var Bk=function(a,b,c){Q.call(this,a,b);this.username=c;this.uri=b;this.value=lc};C(Bk,Q);
Bk.prototype.A=function(){return this.username+ba+this.X.A()+La};Bk.prototype.encode=function(){return this.X.encode()+n+encodeURIComponent(this.uri)+n+encodeURIComponent(this.username)};Bk.prototype.L=function(){return new Ak(this)};var Ak=function(a){this.m=a};C(Ak,Cj);v=Ak.prototype;v.oa=function(){return!0};v.ga=function(){Ak.h.ga.call(this);S(Cf);J(If).innerHTML=this.m.X.vh;for(var a=J(Hf),b=B(function(){this.le()},this),c=[Ad,Ze,Ye,$e,ud,re],d=0;d<c.length;d++)N(a,c[d],b)};
v.Z=function(){Ak.h.Z.call(this);$i(J(Hf));T(Cf);U(6,null,!1);J(Gf).value=e};v.Va=function(){this.rh(this.m.username);J(Gf).value=this.m.X.Jf(this.m.username)};v.Ya=function(){this.m.username=this.jc();this.Va()};v.Cb=function(){return this.jc()==e?(U(6,xc,!0),!1):!0};v.le=function(){var a=this.m.X.gg(),b=this.jc(),b=b==e?Ig:encodeURIComponent(b);J(Df).innerHTML=a[0];J(Ff).innerHTML=b;J(Ef).innerHTML=a[1]};v.jc=function(){return J(Hf).value};v.rh=function(a){J(Hf).value=a;this.le()};var Ck=function(){};
C(Ck,R);Ck.prototype.A=function(){return mc};Ck.prototype.R=function(){return lc};Ck.prototype.decode=function(a){return new Dk(this,a[1])};Ck.prototype.L=function(){return new Ek(new Dk(this,e))};var Dk=function(a,b){Q.call(this,a,b);this.uri=b;this.value=lc};C(Dk,Q);Dk.prototype.A=function(){return this.uri};Dk.prototype.encode=function(){return this.X.encode()+n+encodeURIComponent(this.uri)};Dk.prototype.L=function(){return new Ek(this)};var Ek=function(a){this.m=a};C(Ek,Cj);v=Ek.prototype;
v.oa=function(){return!0};v.ga=function(){Ek.h.ga.call(this);S(we)};v.Z=function(){Ek.h.Z.call(this);T(we);U(7,null,!1);this.De(e)};v.Va=function(){this.De(this.m.uri)};v.Ya=function(){this.m.uri=this.Id()};v.Cb=function(){return this.Id()==e?(U(7,wc,!0),!1):!0};v.Id=function(){return J(Gf).value};v.De=function(a){J(Gf).value=a};var Fk=function(){ik(J(ed),Sf);return!0};var Gk=function(a,b,c){K.call(this);this.vc=a;this.xg=b||0;this.wa=c;this.Ff=B(this.Qf,this)};C(Gk,K);v=Gk.prototype;v.Na=0;v.l=function(){Gk.h.l.call(this);this.stop();delete this.vc;delete this.wa};v.start=function(a){this.stop();this.Na=nj(this.Ff,x(a)?a:this.xg)};v.stop=function(){this.Ab()&&w.clearTimeout(this.Na);this.Na=0};v.Ab=function(){return 0!=this.Na};v.Qf=function(){this.Na=0;this.vc&&this.vc.call(this.wa)};var Hk={},Ik=null,Jk=function(a){a=a[ih]||(a[ih]=++jh);delete Hk[a];Xh(Hk)&&Ik&&Ik.stop()},Lk=function(){Ik||(Ik=new Gk(function(){Kk(mh())},20));var a=Ik;a.Ab()||a.start()},Kk=function(a){Sh(Hk,function(b){b.Og(a)});Xh(Hk)||Lk()};var Mk=function(){O.call(this);this.Ea=0;this.endTime=this.startTime=null};C(Mk,O);v=Mk.prototype;v.qh=function(){this.Ea=1};v.Ce=function(){this.Ea=0};v.Rd=function(){return 1==this.Ea};v.Qd=function(){return-1==this.Ea};v.Sd=function(){return 0==this.Ea};v.Pg=function(){this.S(od)};v.ee=function(){this.S(ee)};v.Vg=function(){this.S(qe)};v.Yg=function(){this.S(Nf)};v.bh=function(){this.S(ag)};v.dh=function(){this.S(rg)};v.S=function(a){this.dispatchEvent(a)};var Nk=function(a,b,c,d){Mk.call(this);if(!z(a)||!z(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.$a=a;this.Uf=b;this.duration=c;this.dd=d;this.coords=[];this.progress=0;this.sc=null};C(Nk,Mk);v=Nk.prototype;
v.play=function(a){if(a||this.Sd())this.progress=0,this.coords=this.$a;else if(this.Rd())return!1;Jk(this);this.startTime=a=mh();this.Qd()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.sc=this.startTime;this.progress||this.Pg();this.Yg();this.Qd()&&this.bh();this.qh();var b=this[ih]||(this[ih]=++jh);b in Hk||(Hk[b]=this);Lk();this.rd(a);return!0};v.stop=function(a){Jk(this);this.Ce();a&&(this.progress=1);this.Ke(this.progress);this.dh();this.ee()};
v.l=function(){this.Sd()||this.stop(!1);this.Sg();Nk.h.l.call(this)};v.Og=function(a){this.rd(a)};v.rd=function(a){E(this.startTime);E(this.endTime);E(this.sc);this.progress=(a-this.startTime)/(this.endTime-this.startTime);1<=this.progress&&(this.progress=1);this.sc=a;this.Ke(this.progress);1==this.progress?(this.Ce(),Jk(this),this.Vg(),this.ee()):this.Rd()&&this.Lg()};
v.Ke=function(a){gh(this.dd)&&(a=this.dd(a));this.coords=Array(this.$a.length);for(var b=0;b<this.$a.length;b++)this.coords[b]=(this.Uf[b]-this.$a[b])*a+this.$a[b]};v.Lg=function(){this.S(gd)};v.Sg=function(){this.S(Sd)};v.S=function(a){this.dispatchEvent(new Ok(a,this))};var Ok=function(a,b){L.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.state=b.Ea};C(Ok,L);var Pk,Qk={yh:"activedescendant",Dh:"atomic",Eh:"autocomplete",Fh:"busy",Hh:Cd,Mh:"controls",Ph:"describedby",Sh:Td,Uh:"dropeffect",Vh:le,Wh:"flowto",Xh:"grabbed",ai:"haspopup",HIDDEN:De,di:"invalid",ei:"label",fi:"labelledby",gi:"level",li:"live",wi:"multiline",xi:"multiselectable",Ci:"orientation",Di:"owns",Ei:"posinset",Gi:"pressed",Ki:"readonly",Mi:"relevant",Ni:"required",Ti:"selected",Vi:"setsize",Xi:"sort",lj:"valuemax",mj:"valuemin",nj:"valuenow",oj:"valuetext"};var Rk={zh:"alert",Ah:"alertdialog",Bh:"application",Ch:"article",BANNER:"banner",BUTTON:wd,Gh:Bd,Ih:"columnheader",Jh:"combobox",Kh:"complementary",Lh:"contentinfo",Oh:"definition",Qh:"dialog",Rh:"directory",Th:"document",FORM:te,Yh:"grid",Zh:"gridcell",$h:"group",bi:"heading",ci:Ue,hi:"link",ii:"list",ji:"listbox",ki:"listitem",mi:"log",ni:"main",oi:"marquee",pi:"math",ri:"menu",si:"menubar",ti:"menuitem",ui:"menuitemcheckbox",vi:"menuitemradio",zi:"navigation",Ai:"note",Bi:Jf,Fi:"presentation",
Hi:"progressbar",Ii:Vf,Ji:"radiogroup",Li:"region",Oi:"row",Pi:"rowgroup",Qi:"rowheader",Ri:"scrollbar",Si:"search",Ui:"separator",Wi:"slider",Yi:"spinbutton",Zi:"status",aj:xg,bj:"tablist",cj:"tabpanel",dj:"textbox",ej:"textinfo",fj:"timer",gj:"toolbar",hj:"tooltip",ij:"tree",jj:"treegrid",kj:"treeitem"};var Sk=function(a){K.call(this);this.wa=a;this.c={}};C(Sk,K);var Tk=[];v=Sk.prototype;v.Aa=function(a,b,c,d){return this.Cg(a,b,c,d)};v.Cg=function(a,b,c,d,f){z(b)||(b&&(Tk[0]=b.toString()),b=Tk);for(var g=0;g<b.length;g++){var k=N(a,b[g],c||this.handleEvent,d||!1,f||this.wa||this);if(!k)break;this.c[k.key]=k}return this};v.uc=function(a,b,c,d){return this.Zd(a,b,c,d)};
v.Zd=function(a,b,c,d,f){if(z(b))for(var g=0;g<b.length;g++)this.Zd(a,b[g],c,d,f);else{a=Xi(a,b,c||this.handleEvent,d,f||this.wa||this);if(!a)return this;this.c[a.key]=a}return this};v.Ob=function(a,b,c,d,f){if(z(b))for(var g=0;g<b.length;g++)this.Ob(a,b[g],c,d,f);else c=c||this.handleEvent,f=f||this.wa||this,c=Ri(c),d=!!d,b=Ji(a)?a.Ma(b,c,d,f):a?(a=Ti(a))?a.Ma(b,c,d,f):null:null,b&&(Zi(b),delete this.c[b.key]);return this};
v.Jb=function(){Sh(this.c,function(a,b){this.c.hasOwnProperty(b)&&Zi(a)},this);this.c={}};v.l=function(){Sk.h.l.call(this);this.Jb()};v.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Uk=function(a,b,c,d,f){function g(a){a&&(a.tabIndex=0,D(Wh(Rk,xg),jc),a.setAttribute(bg,xg),Sj(a,Ae),k.Sf(a),k.Rf(a))}O.call(this);this.hc=f||wi();this.ba=this.hc.rb(a)||null;this.Ka=this.hc.rb(d||null);this.T=(this.Eb=gh(b)?b:null)||!b?null:this.hc.rb(b);this.W=1==c;x(c)||this.Eb||(this.Ka?this.W=this.Ka.style.display!=u:this.ba&&(this.W=Rj(this.ba,ze)));this.Yd=new Sk(this);this.ce=new Sk(this);var k=this;g(this.ba);g(this.Ka);this.Lb(this.W)};C(Uk,O);v=Uk.prototype;
v.l=function(){Uk.h.l.call(this);Ei(this.Yd);Ei(this.ce)};v.collapse=function(){this.Lb(!1)};v.toggle=function(){this.Lb(!this.W)};v.Lb=function(a){this.T?this.T.style.display=a?e:u:a&&this.Eb&&(this.T=this.Eb());this.T&&Sj(this.T,ye);this.Ka?(this.ba.style.display=a?u:e,this.Ka.style.display=a?e:u):this.Lc(a);this.we(a);this.dispatchEvent(new Vk(Dg,this,this.W))};v.we=function(a){this.W=a};
v.Lc=function(a){if(this.ba){var b=this.ba;a?Sj(b,ze):Tj(b,ze);b=this.ba;a?Tj(b,xe):Sj(b,xe);b=this.ba;z(a)&&(a=a.join(h));D(le,Bb);D(Wh(Qk,le),ic);a===e||void 0==a?(Pk||(Pk={atomic:!1,autocomplete:u,dropeffect:u,haspopup:!1,live:xf,multiline:!1,multiselectable:!1,orientation:Kg,readonly:!1,relevant:bd,required:!1,sort:u,busy:!1,disabled:!1,hidden:!1,invalid:oe}),a=Pk,le in a?b.setAttribute(ld,a.expanded):b.removeAttribute(ld)):b.setAttribute(ld,a)}};v.Rf=function(a){a&&this.Yd.Aa(a,Ye,this.Xg)};
v.Sf=function(a){a&&this.ce.Aa(a,Fd,this.Wg)};v.Xg=function(a){if(13==a.keyCode||32==a.keyCode)this.toggle(),this.ud(),a.preventDefault(),a.stopPropagation()};v.Wg=function(){this.toggle();this.ud()};v.ud=function(){this.dispatchEvent(new L($c,this))};var Vk=function(a,b){L.call(this,a,b)};C(Vk,L);var Wk=function(a,b,c,d){d=d||wi();var f=d.dc(Mb,{style:Kf});b=d.rb(b);b.parentNode.replaceChild(f,b);f.appendChild(b);this.nb=f;this.O=null;Uk.call(this,a,b,c,void 0,d);a=this.W;this.nb.style.display=a?e:u;this.Lc(a)};C(Wk,Uk);v=Wk.prototype;v.Df=500;v.Cf=function(a){return 1-Math.pow(1-a,3)};
v.Lb=function(a){if(this.W!=a||this.O){this.nb.style.display==u&&(this.nb.style.display=e);var b=this.T.offsetHeight,c=0;this.O?(a=this.W,$i(this.O),this.O.stop(!1),c=b-Math.abs(parseInt(this.T.style.marginTop,10))):c=a?0:b;this.Lc(a);this.O=new Nk([0,c],[0,a?b:0],this.Df,this.Cf);N(this.O,[od,gd,ee],this.Mg,!1,this);N(this.O,ee,B(this.Ng,this,a));this.O.play(!1)}};v.Mg=function(a){var b=this.T;b.style.marginTop=a.y-b.offsetHeight+Uf};
v.Ng=function(a){a&&(this.T.style.marginTop=cb);$i(this.O);this.we(a);this.O=null;a||(this.nb.style.display=u);this.dispatchEvent(new Vk(Dg,this,a))};var Xk=null;var V=new yk;y("BLOG_CMT_OpenIdIdentityFactory",zk,void 0);y("BLOG_CMT_LoggedInGaiaIdentity",rk,void 0);y("BLOG_CMT_NotLoggedInGaiaIdentityFactory",uk,void 0);y("BLOG_CMT_GenericOpenIdIdentityFactory",Ck,void 0);y("BLOG_CMT_NameUrlIdentityFactory",xk,void 0);y("BLOG_CMT_AnonymousIdentityFactory",Ej,void 0);y("BLOG_CMT_onPost",function(){Fk();return V.Zg()},void 0);y("BLOG_CMT_onPreview",function(){return V.$g()},void 0);y("BLOG_CMT_onCommentBodyChange",function(){},void 0);
y("BLOG_CMT_onCancel",function(){return V.Qg()},void 0);y("BLOG_CMT_onSelectorChange",function(){return V.zc()},void 0);y("BLOG_CMT_onContinue",function(){return V.Rg()},void 0);y("BLOG_CMT_onEdit",function(){return V.Tg()},void 0);y("BLOG_CMT_addIdentity",function(a){return V.$b(a)},void 0);y("BLOG_CMT_addAndSelectIdentity",function(a){return V.ed(a)},void 0);y("BLOG_CMT_addIdentityFactory",function(a){return V.ja(a)},void 0);y("BLOG_CMT_addNameUrlIdentityFactory",function(){return V.zf()},void 0);
y("BLOG_CMT_addAnonIdentity",function(){return V.yf()},void 0);y("BLOG_CMT_addNotLoggedInGaiaIdentity",function(){return V.Af()},void 0);y("BLOG_CMT_init",function(a,b){ck(document.location.href);V.kh();V.zc();V.$d();pk(a,b);J(lg).value==Eg&&(J(lg).value=oe,gk(J(ed),Sf));bk();return!0},void 0);y("BLOG_CMT_addOpenIdIdentityFactories",function(){V.ja(new zk(Wb,Ie,Yb,Zb));V.ja(new zk(Bc,Je,Cc,Dc));V.ja(new zk(vc,Ke,yc,zc));V.ja(new zk(yb,He,yb,zb));V.ja(new Ck)},void 0);
y("BLOG_CMT_createPhotoZippy",function(a,b){J(a)&&J(b)&&(Xk=new Wk(a,b))},void 0);y("BLOG_CMT_closePhotoZippy",function(){null!=Xk&&Xk.collapse()},void 0);y("BLOG_CMT_finalizeBG",function(){window.kd&&window.kd.invoke(function(a){document.getElementById(qd).value=a})},void 0);
y("BLOG_CMT_getBG",function(){var a=new Fj(ab),b=document.getElementById(qd).value;b&&a.Mb(qd,b);b=null;window.navigator.appName==cc&&(document.documentMode?b=document.documentMode:(b=5,document.compatMode&&document.compatMode==Hb&&(b=7)));b&&a.Mb(Re,b);document.getElementById(Mf)&&a.Mb(Lf,db);Pj&&a.Mb(pd,Pj);wj(a,function(){if(this.Sa()){var a=eval(this.dg());a instanceof Object&&a.length&&(1<a.length&&(eval(a[1]),Pj=a[2]),window.kd=new botguard.bg(a[0]))}})},void 0);
y("BLOG_CMT_setBG",function(a){Pj=a},void 0);y("BLOG_CMT_subscription.toggle",function(){if(!mk){mk=!0;var a=J(Kd);wj(a.action,function(){mk=!1;if(this.Sa()){var a=this.Hd();null!=a.errorMessage?U(3,a.errorMessage,!0):dk(a.statusMessage);pk(a.can_subscribe,a.is_subscribed)}else U(3,Cb,!0)},nc,lk(a))}},void 0);y("BLOG_CMT_showStatusMessage",dk,void 0);y("BLOG_CMT_showPostErrorMessage",function(a){U(4,a,!0)},void 0);y("BLOG_CMT_hidePreview",function(){Fk();V.Xa();ak()},void 0);y("BLOG_xhr",P,void 0);
P.send=wj;P.prototype.isSuccess=P.prototype.Sa;P.prototype.getResponseJson=P.prototype.Hd;y("$",J,void 0);function Yk(a){return function(b){var c=-1;try{c=b.status}catch(d){}return 500<=c?(b.responseText.length?document.body.innerHTML=b.responseText:window.alert(LayoutsMessages.SERVER_ERROR),!1):a?a(b):!0}};var $k=function(a,b,c){var d=a.ownerDocument;b=b._GetHelper();var f=b._GetData(),g=c._GetAllData();a=Zk(d,a,q,Pg);a=Zk(d,a,q,Qg);a=Zk(d,a,q,Rg);a=Zk(d,a,q,Og);if(g=g.features&&g.features.widgetVisibility&&f.version&&1<f.version)a.className+=ja,Zk(d,a,q,cf+(f.isVisible?Mg:sf)).setAttribute(Cg,f.visibilityTooltipMessage);var k=Zk(d,a,q,af);if(f[df]){var m=Zk(d,a,q,bf);m.appendChild(d.createTextNode(f[df]));m.setAttribute(Cg,f[bf])}k.appendChild(d.createTextNode(f[af]));a=Zk(d,a,Wc,be);var r=b._GenerateWidgetMetadata();
a.setAttribute(Ee,r.quickEditUrl);a.target=Dd;a.onclick=function(){return c._PopupConfig(d.getElementById(r.instanceId))};g&&(a.className+=da);a.appendChild(d.createTextNode(f[$d]))},Zk=function(a,b,c,d){a=a.createElement(c);a.className=d;b.appendChild(a);return a};var al=function(){this.gh={};this.be={};this.Cc={};this.Mc=null;this.ke=[]};ch(al);al.prototype.Cd=function(a,b){return a+Jc+b+Ua};var bl=function(a){eval(a)};al.prototype.Nd=function(a,b){y(Lc,bl,void 0);this.Mc=a.replace(/\.js$/,e);b&&(this.Cd=b);Ih(this.ke,function(a){this.Eg(a)},this);Mh(this.ke)};al.prototype.ih=function(a,b,c){var d=this.be,f=this.gh;d[a]||(d[a]={});if(c)d[a][b]=c;else if(f[a]){for(b=0;b<f[a].length;++b)(0,f[a][b][1])(d[a][f[a][b][0]]);delete f[a];delete this.Cc[a]}};
al.prototype.Eg=function(a){nj(function(){if(!this.be[a]){Fh(this.Mc);var b=this.Cd(this.Mc,a),c=Wh(this.Cc,b);this.Cc[a]=b;c||(b=Ai(qc,{type:zg,src:b}),document.body.appendChild(b))}},0,this)};var cl=function(){this.J=[];this.P=[]};v=cl.prototype;v.Fg=function(){0==this.J.length&&(this.J=this.P,this.J.reverse(),this.P=[])};v.enqueue=function(a){this.P.push(a)};v.dequeue=function(){this.Fg();return this.J.pop()};v.s=function(){return this.J.length+this.P.length};v.isEmpty=function(){return 0==this.J.length&&0==this.P.length};v.clear=function(){this.J=[];this.P=[]};v.contains=function(a){return F(this.J,a)||F(this.P,a)};
v.remove=function(a){var b;b=this.J;var c=Hh(b,a);0<=c?(Nh(b,c),b=!0):b=!1;return b||Oh(this.P,a)};v.u=function(){for(var a=[],b=this.J.length-1;0<=b;--b)a.push(this.J[b]);for(var c=this.P.length,b=0;b<c;++b)a.push(this.P[b]);return a};var dl=function(a,b){K.call(this);this.ae=a||0;this.Gb=b||10;if(this.ae>this.Gb)throw Error("[goog.structs.Pool] Min can not be greater than max");this.Y=new cl;this.ea=new lj;this.delay=0;this.rc=null;this.fb()};C(dl,K);v=dl.prototype;v.sb=function(){var a=mh();if(!(null!=this.rc&&a-this.rc<this.delay)){var b=this.jh();b&&(this.rc=a,this.ea.add(b));return b}};v.Gc=function(a){return this.ea.remove(a)?(this.Zb(a),!0):!1};
v.jh=function(){for(var a;0<this.Bd()&&(a=this.Y.dequeue(),!this.yc(a));)this.fb();!a&&this.s()<this.Gb&&(a=this.ec());return a};v.Zb=function(a){this.ea.remove(a);this.yc(a)&&this.s()<this.Gb?this.Y.enqueue(a):this.gc(a)};v.fb=function(){for(var a=this.Y;this.s()<this.ae;)a.enqueue(this.ec());for(;this.s()>this.Gb&&0<this.Bd();)this.gc(a.dequeue())};v.ec=function(){return{}};v.gc=function(a){if(typeof a.la==t)a.la();else for(var b in a)a[b]=null};v.yc=function(a){return typeof a.Gf==t?a.Gf():!0};
v.contains=function(a){return this.Y.contains(a)||this.ea.contains(a)};v.s=function(){return this.Y.s()+this.ea.s()};v.Yf=function(){return this.ea.s()};v.Bd=function(){return this.Y.s()};v.isEmpty=function(){return this.Y.isEmpty()&&this.ea.isEmpty()};v.l=function(){dl.h.l.call(this);if(0<this.Yf())throw Error("[goog.structs.Pool] Objects not released");delete this.ea;for(var a=this.Y;!a.isEmpty();)this.gc(a.dequeue());delete this.Y};var el=function(a,b){this.Xd=a;this.Qc=b};el.prototype.getKey=function(){return this.Xd};el.prototype.clone=function(){return new el(this.Xd,this.Qc)};var fl=function(a){this.M=[];a&&this.ug(a)};v=fl.prototype;v.Od=function(a,b){var c=this.M;c.push(new el(a,b));this.Kg(c.length-1)};v.ug=function(a){var b;if(a instanceof fl){if(b=a.K(),a=a.u(),0>=this.s()){for(var c=this.M,d=0;d<b.length;d++)c.push(new el(b[d],a[d]));return}}else b=Uh(a),a=Th(a);for(d=0;d<b.length;d++)this.Od(b[d],a[d])};v.remove=function(){var a=this.M,b=a.length,c=a[0];if(!(0>=b))return 1==b?Mh(a):(a[0]=a.pop(),this.Hg(0)),c.Qc};
v.Hg=function(a){for(var b=this.M,c=b.length,d=b[a];a<c>>1;){var f=this.ag(a),g=this.fg(a),f=g<c&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>d.getKey())break;b[a]=b[f];a=f}b[a]=d};v.Kg=function(a){for(var b=this.M,c=b[a];0<a;){var d=this.cg(a);if(b[d].getKey()>c.getKey())b[a]=b[d],a=d;else break}b[a]=c};v.ag=function(a){return 2*a+1};v.fg=function(a){return 2*a+2};v.cg=function(a){return a-1>>1};v.u=function(){for(var a=this.M,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].Qc);return b};
v.K=function(){for(var a=this.M,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};v.ka=function(a){return Kh(this.M,function(b){return b.getKey()==a})};v.clone=function(){return new fl(this)};v.s=function(){return this.M.length};v.isEmpty=function(){return 0==this.M.length};v.clear=function(){Mh(this.M)};var gl=function(){fl.call(this)};C(gl,fl);gl.prototype.enqueue=function(a,b){this.Od(a,b)};gl.prototype.dequeue=function(){return this.remove()};var hl=function(a,b){this.td=void 0;this.Kb=new gl;dl.call(this,a,b)};C(hl,dl);v=hl.prototype;v.sb=function(a,b){if(!a){var c=hl.h.sb.call(this);c&&this.delay&&(this.td=w.setTimeout(B(this.ub,this),this.delay));return c}this.Kb.enqueue(x(b)?b:100,a);this.ub()};v.ub=function(){for(var a=this.Kb;0<a.s();){var b=this.sb();if(b)a.dequeue().apply(this,[b]);else break}};v.Zb=function(a){hl.h.Zb.call(this,a);this.ub()};v.fb=function(){hl.h.fb.call(this);this.ub()};
v.l=function(){hl.h.l.call(this);w.clearTimeout(this.td);this.Kb.clear();this.Kb=null};var il=function(a,b,c,d){this.mc=a;this.Fa=!!d;hl.call(this,b,c)};C(il,hl);il.prototype.ec=function(){var a=new P,b=this.mc;b&&b.forEach(function(b,d){a.headers.set(d,b)});this.Fa&&a.Jc(!0);return a};il.prototype.yc=function(a){return!a.sa&&!a.Ab()};var jl=function(a,b,c,d,f,g){O.call(this);this.xc=x(a)?a:1;this.qa=x(f)?Math.max(0,f):0;this.Ga=new il(b,c,d,g);this.N=new hj;this.ob=new Sk(this)};C(jl,O);var kl=[Wf,p,wg,fe,Yc,Bg];v=jl.prototype;v.Ic=function(a){this.qa=Math.max(0,a)};v.send=function(a,b,c,d,f,g,k,m,r,ua){if(this.N.get(a))throw Error("[goog.net.XhrManager] ID in use");b=new ll(b,B(this.mg,this,a),c,d,f,k,x(m)?m:this.xc,r,ua);this.N.set(a,b);a=B(this.jg,this,a);this.Ga.sb(a,g);return b};
v.abort=function(a,b){var c=this.N.get(a);if(c){var d=c.Qb;c.mh(!0);b&&(d&&(this.oe(d,c.Rc),Xi(d,Wf,function(){this.Ga.Gc(d)},!1,this)),this.N.remove(a));d&&d.abort()}};v.jg=function(a,b){var c=this.N.get(a);c&&!c.Qb?(this.Bf(b,c.Rc),b.Ic(this.qa),b.ph(c.Ca),b.Jc(c.Fa),c.Qb=b,this.dispatchEvent(new ml(Wf,this,a,b)),this.qe(a,b),c.cd&&b.abort()):this.Ga.Gc(b)};
v.mg=function(a,b){var c=b.target;switch(b.type){case Wf:this.qe(a,c);break;case p:return this.kg(a,c,b);case wg:this.ng(a,c);break;case Bg:case fe:this.lg(a,c);break;case Yc:this.ig(a,c)}return null};v.qe=function(a,b){var c=this.N.get(a);!c||c.pd||c.lc()?(c&&(this.oe(b,c.Rc),this.N.remove(a)),this.Ga.Gc(b)):(c.sg(),b.send(c.getUrl(),c.Gg,c.getContent(),c.mc))};
v.kg=function(a,b,c){var d=this.N.get(a);if(7==b.za||b.Sa()||d.lc())if(this.dispatchEvent(new ml(p,this,a,b)),d&&(d.nh(!0),d.od))return d.od.call(b,c);return null};v.ig=function(a,b){this.dispatchEvent(new ml(Yc,this,a,b))};v.ng=function(a,b){this.dispatchEvent(new ml(wg,this,a,b))};v.lg=function(a,b){this.N.get(a).lc()&&this.dispatchEvent(new ml(fe,this,a,b))};v.oe=function(a,b,c){this.ob.Ob(a,c||kl,b)};v.Bf=function(a,b,c){this.ob.Aa(a,c||kl,b)};
v.l=function(){jl.h.l.call(this);this.Ga.la();this.Ga=null;this.ob.la();this.ob=null;this.N.clear();this.N=null};var ml=function(a,b,c,d){L.call(this,a,b);this.id=c;this.Qb=d};C(ml,L);var ll=function(a,b,c,d,f,g,k,m,r){this.uh=a;this.Gg=c||Rb;this.Kf=d;this.mc=f||null;this.xc=x(k)?k:1;this.jd=0;this.cd=this.pd=!1;this.Rc=b;this.od=g;this.Ca=m||e;this.Fa=!!r;this.Qb=null};v=ll.prototype;v.getUrl=function(){return this.uh};v.getContent=function(){return this.Kf};v.sg=function(){this.jd++};
v.lc=function(){return this.jd>this.xc};v.nh=function(a){this.pd=a};v.mh=function(a){this.cd=a};function nl(a,b,c,d,f,g){this.Qa=a;this.te=b;this.se=d||null;this.data=f||null;if(g){if(this.fc=g,g!=Yd&&g!=Vd&&g!=Wd&&g!=Xd)throw"bad display mode: "+g;}else this.fc=Xd;this.Bb=!1}nl.prototype.$f=function(){return this.Qa};function ol(a){this.Pf=!0;this.C=a;this.Pb=null}v=ol.prototype;v.sf=function(a){this.Pb=a};v.Ve=function(){return this.C.data};v.mf=function(a){return this.C.data=a};v.pf=function(a){return this.C.Bb=a};
v.Se=function(){var a={};a.type=this.Pb.Ie;a.instanceId=this.C.Qa;a.sectionId=this.C.te;a.actionUrl=W.bc;a.quickEditUrl=W.xd+Ga+this.Pb.Ie+Fa+this.C.Qa+Ea+this.C.te+xa+W.Uc;return a};v.Xb=function(a,b,c,d){b=b||{};window.__wavt&&(b.xssi_token=window.__wavt);W.Xb(a,b,this.C.Qa,this.Pb.Ie,c,d)};function W(){}W.Ze=function(a,b,c){W.ha={};W.xd=a;W.bc=b;W.qj=c;W.kc={};W.Rb=new jl;W.de=0;W.Dc=0;N(W.Rb,Wf,function(){W.Dc++});N(W.Rb,p,function(){W.Dc--})};W.uf=function(a){a=W.Pe(a.document);document.body.appendChild(a)};
W.tf=function(a){W.uf(window);if(window.parent==window){var b=pc;a&&(b=a);a=W.Oe(window.document,b);document.body.appendChild(a[0]);document.body.appendChild(a[1])}};W.af=Dd;W.Ne=Dd;W.Uc="editWidget";W.Ue=function(){return W.bc};W.qf=function(a,b){W.Ac=a;W.fh=b};W.Xe=function(){return W.Ac};W.rf=function(a){W.xh=a};W.Vc=function(){return W.xh};W.nf=function(a){W.kc=a};W.Te=function(){var a={},b;for(b in W.kc){var c=W.kc[b];a[c.name]=c.data}c={};for(b in W.ha)c[b]=W.ha[b].B.C.data;a.widgets=c;return a};
W.Xc=function(a,b){var c=new ol(b),d=new window[a](c);c.sf(d);W.ha[b.Qa]=d;W.Tc(d);return d};W.gf=function(a,b){var c=W.Xc(a,b);c.B.pf(!0);return c};W.Tc=function(a){a.B.C.fc!=Xd&&(a.B.Pf=!1)};W.ra=function(a){return W.ha?W.ha[a]:null};W.Wb=function(a,b,c,d,f){var g=e;d&&(g=Fa+d);a=W.xd+xa+a+Ea+b+Ga+c+g;if(window.name==f)return window.location.replace(a),window.focus(),window;f=window.open(a,f,Vg);f.focus();return f};
W.ef=function(a){var b=a.getAttribute(Le),c=W.ra(b);if(c){var d=c.B.Ja;if(null!=d&&!d.closed)return d.focus(),!1}d=Md+b;a=W.Wb(W.Uc,a.parentNode.getAttribute(Le),a.getAttribute(Tg),b,d);c&&(c.B.Ja=a);return!1};W.ff=function(a){W.Wb(W.Ne,a.parentNode.getAttribute(Le),a.getAttribute(Tg),a.getAttribute(Le),W.af);return!1};W.Qe=function(a,b,c){W.ia(c,c.LayoutsMessages.DELETING);W.Zc(Rd,{},a,b)};ol.prototype.jf=function(a,b){W.ia(b,b.LayoutsMessages.SAVING);this.Xb(Nd,a)};
W.kf=function(a,b,c){a.sectionid=document.getElementById(dg).value;W.ia(c,c.LayoutsMessages.SAVING);W.Zc(cd,a,e,b)};W.$i=function(a,b,c){D(null!=c,qf);var d=W.ra(b);D(null!=d,rf+b);d.B.C.Bb?W.kf(a,c,window):d.B.jf(a,window)};W.Xb=function(a,b,c,d,f,g){W.Yc(W.bc,a,b,c,d,f,g)};W.Zc=function(a,b,c,d,f){W.Ac&&(b.security_token=W.fh,W.Yc(W.Ac,a,b,c,d,f))};
W.Yc=function(a,b,c,d,f,g,k){b=[ad+encodeURIComponent(b),Sg+encodeURIComponent(d),Ug+encodeURIComponent(f),$f];for(var m in c)if(typeof c[m]==wf)for(d=c[m],f=0;f<d.length;++f)b.push(encodeURIComponent(m)+n+encodeURIComponent(d[f]));else b.push(encodeURIComponent(m)+n+encodeURIComponent(c[m]));var r=g||Yk();c=function(){r(this.a)&&window.eval(this.eg())};k==Rb?(a=0<=a.indexOf(vb)?a+l:a+vb,W.Rb.send(e+W.de++,a+b.join(l),Rb,void 0,null,null,c)):W.Rb.send(e+W.de++,a,nc,b.join(l),null,null,c)};
W.lf=function(a,b){if(a){var c=W.ra(a);c&&(c.B.Ja=b)}};W.cb=function(a,b){0==W.Dc?a.setTimeout(function(){a.close()},b):a.setTimeout(function(){W.cb(a,b)},200)};W.$e=function(a,b){a&&(W.cb(a,100),W.vf(a,b))};W.vf=function(a,b){if(a){var c=a.document.getElementById(qg);c&&(c=c.innerHTML);c&&a&&a.opener.parent&&a.opener.parent.editor&&a.opener.parent.editor.SetSaveMessage(c,b)}};
W.Wc=function(a,b,c){var d=W.ha[a];null!=c.errors?((a=d?d.B.Ja:null)||(a=window),W.ia(a,c.errors),d&&d.eb?d.eb(b,c,a):W.eb(c,a)):(D(null!=d,rf+a),d.Wc(b,c))};W.eb=function(a,b){var c=a[ge],d;for(d in c)pl(d,c[d],b.document)};W.bf=function(a,b){window.parent&&window.parent.editor&&b?W.cf(a,b):window.location.replace(window.location.href)};W.cf=function(a,b){var c=W.ra(a);c.B.mf(b.data);var d=document.getElementById(a);Di(d);$k(d,c,W);c.B.Ja=null};
W.Ye=function(a,b,c){var d=c[pg];if(null!=c.errors)W.ia(window,c.errors),W.eb(c,window);else if(b==cd){var f;W.Ub(window)&&(window.opener&&window.opener.parent&&(f=window.opener.parent),f&&f.editor&&f.editor.HandleAddNewWidget(c));W.ia(window,d);null==window.opener?window.location=bb+c.blogID:f&&f._WidgetManager?f._WidgetManager._KillPopupDelay(window):W.cb(window,100)}else c=W.ha[a],D(null!=c),b==Rd&&(W.ia(c.B.Ja,d),W.Re(a,Kc))};
W.df=function(a){var b=W.ra(a);b&&(b.B.C.fc==Wd?top.editor.HandleDeleteWidget(b.B.C.se):(b=b.B.C.se,b.parentNode.removeChild(b)),delete W.ha[a])};W.Re=function(a,b,c){if(W.Ub(window)){var d=window.opener;c||(c=d._WidgetManager[b]);c(a);d._WidgetManager?d._WidgetManager._KillPopupDelay(window,a):W.cb(window,100)}else a=W.Vc()+wb+a,a+=za+encodeURIComponent(b),window.location.replace(a)};W.Ub=function(a){var b=!1;try{if(a.opener){var c=Ec+a.opener.document.domain;c&&c!=Ec&&(b=!0)}}catch(d){}return b};
W.$c="status-msg-yellow-on-white";W.ia=function(a,b){a||(a=self);var c=a.document.getElementById(qg);c&&(c.innerHTML=b);(c=a.document.getElementById(pg))&&gk(c,W.$c)};W.Nh=function(a){a||(a=self);(a=a.document.getElementById(pg))&&ik(a,W.$c)};W.yi=function(a){a&&0<a.length&&a.substring(0,4)!=Fe&&(a=Ge+a);return a};W.We=function(a,b){if(F(fk(a),b))return a;if(a)for(var c=a.childNodes.length,d=0;d<c;d++){var f=W.We(a.childNodes.item(d),b);if(f)return f}return null};
W.Pe=function(a){a=a.createElement(q);a.className=td;a.style.position=Zc;a.style.top=cb;a.style.left=cb;a.style.width=eb;a.style.height=eb;H&&!I(7)&&(a.style.height=ne);a.style.zIndex=fb;a.style.cursor=Qd;a.onclick=W.Vb;a.onmousedown=W.Vb;a.onmouseup=W.Vb;a.style.background=Ng;a.style.filter=fd;a.style.opacity=Ra;a.innerHTML=Ca;return a};
W.Oe=function(a,b){var c=W.Sc(a,b),d=W.Sc(a,b);c.style.backgroundColor=oa;c.style.border=hb;H&&(c.style.filter=ha);c.style.opacity=Ta;d.style.border=ib;c.style.zIndex=1200;d.style.zIndex=1200;return[c,d]};
W.Sc=function(a,b){var c=a.createElement(q);c.style.position=Zc;c.style.top=ob;c.style.left=Pa;c.style.width=nb;c.style.height=lb;c.style.margin=cb;c.style.padding=gb;c.style.fontSize=kb;c.style.textAlign=zd;c.style.color=pa;c.style.fontFamily=ma;H&&(c.style.top=Oa,c.style.left=Oa,c.style.filter=fa);c.style.MozTransform=cg;c.style.MozTransformOrigin=mb;c.style.WebkitTransform=cg;c.style.WebkitTransformOrigin=mb;c.innerHTML=b;c.className=mg;return c};
W.Vb=function(a){a||(a=window.event);a&&(a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation());return!1};var ql=function(a,b){b||(b=document);return b.getElementById(je+a)},rl=function(a){if(a=ql(a))Di(a),a.className=ie},pl=function(a,b,c){if(a=ql(a,c))a.innerHTML=b,a.className=he};y("_WidgetManager",W,void 0);W._Init=W.Ze;W._SetPageActionUrl=W.qf;W._GetPageActionUrl=W.Xe;W._SetWidgetRefreshUrl=W.rf;W._GetWidgetRefreshUrl=W.Vc;W._GetCallbackUrl=W.Ue;W._DeleteWidgetFromPage=W.Qe;
W._DisplayWidget=W.Tc;W._GetWidget=W.ra;W._HandleControllerResult=W.Wc;W._HandlePageActionResult=W.Ye;W._IsOpenerReachable=W.Ub;W._SetConfigWin=W.lf;W._SetDataContext=W.nf;W._SetupPreview=W.tf;W._RegisterWidget=W.Xc;W._RegisterNewWidget=W.gf;W._PopupPaneFromParams=W.Wb;W._PopupConfig=W.ef;W._PopupToolbox=W.ff;W._KillPopupDelay=W.$e;W._OnWidgetConfigured=W.bf;W._OnWidgetDeleted=W.df;y("_WidgetInfo",nl,void 0);nl.prototype._getInstanceId=nl.prototype.$f;ol.prototype._GetData=ol.prototype.Ve;
ol.prototype._GenerateWidgetMetadata=ol.prototype.Se;W._GetAllData=W.Te;y("widget_module_provide",function(a,b,c){al.Zf().ih(a,b,c)},void 0);function X(a,b,c,d,f,g,k,m){this.F=a;this.ld=b!=tf?b:null;this.Vd=c;this.Td=d;this.Ud=f;this.ue=g;this.Wd=k;this.lh=m;this.xb=this.xa=-1;this.oc=null;this.Wa=300;this.wc=jb;this.I=document.getElementById(this.F+Vc);this.jb=document.getElementById(this.F+Nc);this.wb=document.getElementById(this.F+Oc);this.pc=document.getElementById(this.F+Rc);this.Md=document.getElementById(this.F+Sc);this.f=document.getElementById(this.F+Qc);this.Oa=document.getElementById(this.F+Uc);this.hd=window.frames[this.F+
Mc];this.nc=0;this.v=new Image;this.v.onload=B(this.eh,this);this.v.onerror=B(this.Ug,this);this.zd=!1;this.ua=this.w=this.Db=null;this.Fc=!1}v=X.prototype;
v.eh=function(){this.nc=0;rl(this.F+Tc);rl(this.F+Pc);this.pc.checked&&0!=this.xa||(this.xa=this.v.width,this.xb=this.v.height,this.oc=this.v.src);var a=1,b=1;this.v.width>this.Wa&&(a=this.Wa/this.v.width);this.v.height>this.Wa&&(b=this.Wa/this.v.height);a=Math.min(a,b);this.I.style.width=Math.round(this.v.width*a)+Uf;this.I.style.height=Math.round(this.v.height*a)+Uf;this.I.src=this.v.src;this.I.style.display=e;this.wb.style.display=u;this.jb.style.display=e;this.f.disabled=!0;this.Vd&&this.Vd.call({},
this.I.src,this.oc,this.xa,this.xb)};v.Za=function(a,b,c,d){a?(pl(this.F+Pc,b),rl(this.F+Tc)):(pl(this.F+Tc,b),rl(this.F+Pc));this.I.style.display=u;this.wb.style.display=e;this.jb.style.display=u;this.f.disabled=!1;this.Td&&this.Td.call({},c,d)};v.Ug=function(){if(2>this.nc){this.nc++;var a=this.v.src;this.v.src=e;this.Ta(a)}else this.Za(this.pc.checked,WidgetMessages.SIV_INVALID_URL,this.I.src,[])};v.Ta=function(a){this.Ge();this.v.src=a};
v.Hf=function(a){a=a||window.event;window.event?(a.returnValue=!1,a.cancelBubble=!0):(a.preventDefault(),a.stopPropagation());this.I.style.display=u;this.jb.style.display=u;this.wb.style.display=e;this.f.disabled=!1;this.Oa.value=e;this.pe();this.Fc=!0;this.Ud&&this.Ud.call({})};v.qg=function(){this.pc.checked=Eg;this.Oa.value=e;this.Ge();this.Jg();this.zd=!0;try{this.w.submit()}catch(a){this.Za(!0,WidgetMessages.SIV_INVALID_URL,this.w.value,[])}this.Ig()};
v.cc=function(){var a=this.hd.document.result;if(a)if(a.hasErrors)0<a.errors.length?this.Za(!0,a.errors[0].message,this.f.value,a.errors):this.Za(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,a.errors);else{var b=Math.max(a.origWidth,a.origHeight),c=this.Kd();0!=this.xa&&-1!=c&&b>c?(b=c/b,this.xa=Math.round(a.origWidth*b),this.xb=Math.round(a.origHeight*b)):(this.xa=a.origWidth,this.xb=a.origHeight);this.oc=a.mainSrc;this.Ta(a.thumbSrc)}else this.Za(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,
[])};v.rg=function(a){9!=(a||window.event).keyCode&&(this.Md.checked=Eg,null!=this.Db&&(window.clearTimeout(this.Db),this.Db=null),a=B(this.Bg,this),this.Db=window.setTimeout(a,1E3))};v.Bg=function(){if(this.Fc||this.v.src!=this.Oa.value)this.pe(),this.Ta(this.Oa.value);this.Fc=!1};v.Dg=function(a){this.Md.checked=!0;this.Oa.value=a;this.Ta(a)};
v.Ge=function(){this.I.src=$a;this.I.style.width=this.wc;this.I.style.height=this.wc;this.I.style.display=e;this.wb.style.display=u;this.jb.style.display=u};
v.Jg=function(){if(!this.w){this.w=document.createElement(te);this.w.action=Te;this.w.method=nc;this.w.target=this.hd.name;this.w.encoding=mf;this.w.style.display=u;if(this.ld){var a=document.createElement(Xe);a.type=De;a.name=sd;a.value=this.ld;this.w.appendChild(a)}a=document.createElement(Xe);a.type=De;a.name=eg;a.id=eg;this.w.appendChild(a);a=document.createElement(Xe);a.type=De;a.name=fg;a.value=this.lh;this.w.appendChild(a);document.body.appendChild(this.w)}a=this.Kd();-1==a&&(a=1600);document.getElementById(eg).value=
a;this.ua={parent:this.f.parentNode,nextSibling:this.f.nextSibling};this.f.parentNode.removeChild(this.f);this.w.appendChild(this.f)};v.oh=function(a){this.Wa=a;this.wc=a+Uf};v.Ig=function(){this.w.removeChild(this.f);this.ua&&this.ua.nextSibling?this.ua.parent.insertBefore(this.f,this.ua.nextSibling):this.ua.parent.appendChild(this.f)};
v.pe=function(){var a=document.createElement(Xe);a.type=pe;a.name=this.f.name;a.id=this.f.id;a.onchange=this.f.onchange;var b=this.f.nextSibling;null==b?this.f.parentNode.appendChild(a):this.f.parentNode.insertBefore(a,b);this.f.parentNode.removeChild(this.f);this.f=a};v.Kd=function(){return-1==this.ue&&this.Wd?this.Wd():this.ue};function Z(){this.Pc={}}var sl=new Z;Z.prototype.Lf=function(a,b,c,d,f,g,k,m){this.Pc[a]=new X(a,b,eval(c),eval(d),eval(f),g,eval(k),m);return this.Pc[a]};
Z.prototype.Jd=function(a){return this.Pc[a]};Z.prototype.cc=function(a){(a=this.Jd(a))&&a.zd&&a.cc()};y("_UploadSimpleImage",sl,void 0);Z.prototype._createUsiContainer=Z.prototype.Lf;Z.prototype._getUsiContainer=Z.prototype.Jd;Z.prototype._channelResultArrived=Z.prototype.cc;X.prototype._changeImage=X.prototype.Hf;X.prototype._imgUrlFileOnChange=X.prototype.qg;X.prototype._imgUrlTextOnKeyUp=X.prototype.rg;X.prototype._loadInitialUrl=X.prototype.Dg;X.prototype._loadImageFromUrl=X.prototype.Ta;
X.prototype._setPreviewSize=X.prototype.oh; })()
